### ISSUE TITLE
service role cannot bypass row-level security

### ISSUE THREAD

**Issue by MarybethGasman** [supabase-community/supabase-kt#142]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

0.9.3

### Target(s)

Android

### What happened? (include your code)

I use service_role key and wish to bypass row-level security, but I got error.

```js

  var client = createSupabaseClient(supabaseUrl = "url",
      supabaseKey = "service_role"
  ){
      install(Postgrest)
  }
  client.postgrest["xxx"].insert(
          xxx, returning = Returning.MINIMAL
 )
```

```js

io.github.jan.supabase.exceptions.UnauthorizedRestException: new row violates row-level security policy for table "xxx"
2023-05-14 23:06:27.382 12035-12035 System.err              pid-12035                            W  URL: xxx
2023-05-14 23:06:27.382 12035-12035 System.err              pid-12035                            W  Headers: xxx
2023-05-14 23:06:27.382 12035-12035 System.err              pid-12035                            W  Http Method: POST
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at io.github.jan.supabase.postgrest.PostgrestImpl.parseErrorResponse(Postgrest.kt:97)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:40)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:40)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at io.github.jan.supabase.network.SupabaseApi.rawRequest$suspendImpl(SupabaseApi.kt:21)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at io.github.jan.supabase.network.SupabaseApi$rawRequest$1.invokeSuspend(Unknown Source:15)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at android.os.Handler.handleCallback(Handler.java:883)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at android.os.Handler.dispatchMessage(Handler.java:100)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at android.os.Looper.loop(Looper.java:227)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at android.app.ActivityThread.main(ActivityThread.java:7550)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at java.lang.reflect.Method.invoke(Native Method)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
2023-05-14 23:06:27.383 12035-12035 System.err              pid-12035                            W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

```

**Comment by MarybethGasman** [comment]
Thank you, It works.
