### ISSUE TITLE
[Bug]: Initialise supposeClient realtime

### ISSUE THREAD

**Issue by bhavinmac** [supabase-community/supabase-kt#17]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

class SplashKotlinActivity : AppCompatActivity() {

    val supabaseClient = createSupabaseClient {
        supabaseUrl = "https://MY_KEY.supabase.co/realtime/v1"
        supabaseKey = "SUPABASE_KEY"

        install(Realtime)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_splash)
        initializeAndroid(supabaseClient)
}

Run app and it crases and trows errro: java.lang.ExceptionInInitializerError

### Platform(s)

Android

### Relevant log output

```shell
java.lang.ExceptionInInitializerError
        at io.ktor.client.HttpClientJvmKt.HttpClient(Unknown Source:0)
        at io.github.jan.supacompose.SupabaseClientImpl.<init>(SupabaseClient.kt:94)
        at io.github.jan.supacompose.SupabaseClientBuilder.build(SupabaseClientBuilder.kt:30)
        at com.wweevv.SplashKotlinActivity.<init>(SplashKotlinActivity.kt:65)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3389)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3620)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7617)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
     Caused by: java.lang.IllegalStateException: Failed to find HTTP client engine implementation in the classpath: consider adding client engine dependency.
```

**Comment by brezinajn** [comment]
add this dependency
```
implementation("io.ktor:ktor-client-cio:2.1.1")
```

**Comment by jan-tennert** [comment]
Yes you need a Ktor Engine, might include this in the readme

**Comment by bhavinmac** [comment]
> add this dependency
> 
> ```
> implementation("io.ktor:ktor-client-cio:2.1.1")
> ```

Now getting error "java.lang.IllegalStateException: The schema must be specified"

**Comment by jan-tennert** [comment]
Also the supabase url should just be **https://MY_KEY.supabase.co**
If you want to have a different URL just for realtime, you can change it in the realtime config but supabase-kt 

> ### General Info
> 
>     * [x]  I installed the latest version of Supabase-Kt
> 
>     * [x]  I checked for similar bug report
> 
> 
> ### What happened? (include your code)
> 
> class SplashKotlinActivity : AppCompatActivity() {
> 
> ```
> val supabaseClient = createSupabaseClient {
>     supabaseUrl = "https://MY_KEY.supabase.co/realtime/v1"
>     supabaseKey = "SUPABASE_KEY"
> 
>     install(Realtime)
> }
> 
> override fun onCreate(savedInstanceState: Bundle?) {
>     super.onCreate(savedInstanceState)
>     setContentView(R.layout.activity_splash)
>     initializeAndroid(supabaseClient)
> ```
> 
> }
> 
> Run app and it crases and trows errro: java.lang.ExceptionInInitializerError
> ### Platform(s)
> 
> Android
> ### Relevant log output
> 
> ```shell
> java.lang.ExceptionInInitializerError
>         at io.ktor.client.HttpClientJvmKt.HttpClient(Unknown Source:0)
>         at io.github.jan.supacompose.SupabaseClientImpl.<init>(SupabaseClient.kt:94)
>         at io.github.jan.supacompose.SupabaseClientBuilder.build(SupabaseClientBuilder.kt:30)
>         at com.wweevv.SplashKotlinActivity.<init>(SplashKotlinActivity.kt:65)
>         at java.lang.Class.newInstance(Native Method)
>         at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
>         at android.app.Instrumentation.newActivity(Instrumentation.java:1272)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3389)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3620)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at android.os.Looper.loop(Looper.java:241)
>         at android.app.ActivityThread.main(ActivityThread.java:7617)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
>      Caused by: java.lang.IllegalStateException: Failed to find HTTP client engine implementation in the classpath: consider adding client engine dependency.
> ```

**Comment by jan-tennert** [comment]
> > add this dependency
> > ```
> > implementation("io.ktor:ktor-client-cio:2.1.1")
> > ```
> 
> Now getting error "java.lang.IllegalStateException: The schema must be specified"

This exception is thrown if you try to listen for db changes without actually specifying a schema. 
See https://github.com/supabase-community/supabase-kt/tree/master/Realtime under Listening for Postgres changes for more informations

**Comment by brezinajn** [comment]
This actually bugs me. Even though I like the DSL style for settings, it doesn't force the consumer to provide required arguments and results in crash at runtime and it increases difficulty for new users. So maybe we should force required args as function arguments.
e. g.
``` Kotlin
createSupabaseClient(
    supabaseUrl = "https://MY_KEY.supabase.co/realtime/v1"
    supabaseKey = "SUPABASE_KEY"
) {
    install(Realtime)
    ...
}
```

**Comment by jan-tennert** [comment]
> This actually bugs me. Even though I like the DSL style for settings, it doesn't force the consumer to provide required arguments and results in crash at runtime and it increases difficulty for new users. So maybe we should force required args as function arguments. e. g.
> 
> ```kotlin
> createSupabaseClient(
>     supabaseUrl = "https://MY_KEY.supabase.co/realtime/v1"
>     supabaseKey = "SUPABASE_KEY"
> ) {
>     install(Realtime)
>     ...
> }
> ```
> 
> Even more so now when this library is part of supabase community (congrats btw :) great job). So there is actually a danger of people using it :D

Thanks, yea you are right, maybe I should change that!

**Comment by jan-tennert** [comment]
I'd close this issue to keep things on topic. Feel free to open another issue when you have any issues!
