### ISSUE TITLE
[Bug]: io.github.jan.supabase.exceptions.BadRequestRestException: Error (headers must have required property 'authorization')

### ISSUE THREAD

**Issue by ShehanAT** [supabase-community/supabase-kt#170]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

'io.github.jan-tennert.supabase:storage-kt:1.0.0', 'io.ktor:ktor-client-android:2.3.0'

### Target(s)

Gradle JDK: 11, Android Grade Plugin Version: 7.4.2, Gradle Version: 7.5

### What happened? (include your code)

I'm running into the following error when trying to use the `upload()` method in this library:
```
FATAL EXCEPTION: main
Process: com.coding.informer.dictionary_app_v3, PID: 23547
io.github.jan.supabase.exceptions.BadRequestRestException: Error (headers must have required property 'authorization')
URL: https://juessugxmpdtjuexmdwj.supabase.co/storage/v1/object/bookmarked_words/
Headers: [x-upsert=[false], apikey=[<Removed for security reasons>], Accept=[application/json], Accept-Charset=[UTF-8]]
Http Method: POST
 at io.github.jan.supabase.storage.StorageImpl.parseErrorResponse(Storage.kt:271)
 at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:62)
 at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:62)
 at io.github.jan.supabase.network.SupabaseApi.rawRequest$suspendImpl(SupabaseApi.kt:25)
 at io.github.jan.supabase.network.SupabaseApi$rawRequest$1.invokeSuspend(Unknown Source:15)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
 at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:345)
 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:135)
 at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:109)
 at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
 at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:59)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7656)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b6b5375, Dispatchers.Main.immediate]
```

**Background Information:** 
I have instanstiated a `SupabaseClient` instance via:
```
val client = createSupabaseClient(
      supabaseUrl = BuildConfig.supabase_project_url,
      supabaseKey = BuildConfig.supabase_project_api_key,

  ) {
      HttpHeaders.Authorization
      //...
      install(Storage) {

      }
  }
```
And using `storage.get(bucketId = '')` works:
```
val bookmarked_works_bucket : BucketApi = client.storage.get(bucketId = "bookmarked_words")
```

It is only when I try to upload an object to the Supabase Bucket via the following line that I'm running into the aforementioned error.:
```
bookmarked_works_bucket.upload("", "sampleWord".toByteArray())
```

Note: I've removed the actual `apikey` value from the above error message for security reasons.

### Steps To Reproduce (optional)

Here is the GitHub repo where you can find the code that is causing this error in file `MainActivity.kt` ln 146: https://github.com/ShehanAT/Dictionary-App-Android

### Relevant log output (optional)

```shell
37 23547-23571 goldfish-address-space  com...ng.informer.dictionary_app_v3  D  allocate: ioctl allocate returned offset 0x3f3ffe000 size 0x2000
2023-06-01 21:44:15.242 23547-23571 HostConnection          com...ng.informer.dictionary_app_v3  D  HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
2023-06-01 21:44:15.288 23547-23571 OpenGLRenderer          com...ng.informer.dictionary_app_v3  I  Davey! duration=803ms; Flags=1, IntendedVsync=57415633159483, Vsync=57416283159457, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=57416287478520, AnimationStart=57416287509020, PerformTraversalsStart=57416287849120, DrawStart=57416394769020, SyncQueued=57416409274120, SyncStart=57416410760320, IssueDrawCommandsStart=57416410907220, SwapBuffers=57416436107120, FrameCompleted=57416438289820, DequeueBufferDuration=328500, QueueBufferDuration=586200, GpuCompleted=0, 
2023-06-01 21:44:15.896 23547-23547 AndroidRuntime          com...ng.informer.dictionary_app_v3  E  FATAL EXCEPTION: main
Process: com.coding.informer.dictionary_app_v3, PID: 23547
io.github.jan.supabase.exceptions.BadRequestRestException: Error (headers must have required property 'authorization')
URL: https://juessugxmpdtjuexmdwj.supabase.co/storage/v1/object/bookmarked_words/
Headers: [x-upsert=[false], apikey=[<Removed for security reasons>], Accept=[application/json], Accept-Charset=[UTF-8]]
Http Method: POST
 at io.github.jan.supabase.storage.StorageImpl.parseErrorResponse(Storage.kt:271)
 at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:62)
 at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:62)
 at io.github.jan.supabase.network.SupabaseApi.rawRequest$suspendImpl(SupabaseApi.kt:25)
 at io.github.jan.supabase.network.SupabaseApi$rawRequest$1.invokeSuspend(Unknown Source:15)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
 at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:345)
 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:135)
 at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:109)
 at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
 at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:59)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7656)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b6b5375, Dispatchers.Main.immediate]
2023-06-01 21:44:15.919 23547-23547 Process                 com...ng.informer.dictionary_app_v3  I  Sending signal. PID: 23547 SIG: 9
---------------------------- PROCESS ENDED (23547) for package com.coding.informer.dictionary_app_v3 ----------------------------
---------------------------- PROCESS STARTED (24038) for package com.coding.informer.dictionary_app_v3 ----------------------------
2023-06-01 21:50:12.644 24038-24038 ctionary_app_v          com...ng.informer.dictionary_app_v3  W  Accessing hidden method Landroid/content/res/ResourcesKey;-><init>(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;ILandroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;[Landroid/content/res/loader/ResourcesLoader;)V (blacklist, linking, denied)
2023-06-01 21:50:12.644 24038-24038 ctionary_app_v          com...ng.informer.dictionary_app_v3  W  Accessing hidden field Landroid/content/res/ResourcesKey;->mLibDirs:[Ljava/lang/String; (greylist-max-o, linking, denied)
2023-06-01 21:50:12.644 24038-24038 ctionary_app_v          com...ng.informer.dictionary_app_v3  W  Accessing hidden field Landroid/content/res/ResourcesKey;->mLibDirs:[Ljava/lang/String; (greylist-max-o, linking, denied)
2023-06-01 21:50:12.644 24038-24038 ctionary_app_v          com...ng.informer.dictionary_app_v3  W  Accessing hidden field Landroid/content/res/ResourcesKey;->mOverlayDirs:[Ljava/lang/String; (greylist-max-o, linking, denied)
2023-06-01 21:50:12.644 24038-24038 ctionary_app_v          com...ng.informer.dictionary_app_v3  W  Accessing hidden field Landroid/content/res/ResourcesKey;->mDisplayId:I (greylist-max-o, linking, denied)
```

**Comment by ShehanAT** [comment]
Let me know if you need further information regarding this error

**Comment by jan-tennert** [comment]
Quick question: Do you have the GoTrue plugin installed? Normally, if you don't have an active session, supabase-kt will just use the api key as authentication, but I just saw that only happens if GoTrue is installed. Will fix that definitely.

**Comment by ShehanAT** [comment]
Yes, I'm able to use the `upload()` method fine after adding the GoTrue plugin to the project.

**Side note:** after adding the GoTrue plugin I still got a `Invalid JWT - new row violates row-level security policy for table "objects"` error but I was able to fix that by adding a new policy on the Supabase dashboard(SQL expression for it: `(bucket_id = 'insert-bucket-name'::text)`)

Thanks a lot for the help!
