### ISSUE TITLE
[Bug]: Storage keeps throwing UnauthorizedRestException when upsert new image with the same name

### ISSUE THREAD

**Issue by hieuwu** [supabase-community/supabase-kt#171]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

1.0.0

### Target(s)

jvmTarget 1.8 and Android 33

### 🖼 Description
I'm using Storage to upload image to bucket in Supabase. However, when I try with upsert true, it keeps throwing UnauthorizedRestException although I already enable every policies in the bucket.
Everything works well with the option upsert is false

### Supabase bucket Policies
**storage.objects Policies**
<img width="1161" alt="Screen Shot 2023-06-03 at 14 02 36" src="https://github.com/supabase-community/supabase-kt/assets/43868345/8e288bc4-4ff2-47f0-a7b8-9d340b204fab">

<img width="1154" alt="Screen Shot 2023-06-03 at 14 02 54" src="https://github.com/supabase-community/supabase-kt/assets/43868345/6999c5ca-cc4f-40da-9899-105715beae68">

**storage.buckets Policies**
<img width="1158" alt="Screen Shot 2023-06-03 at 14 04 05" src="https://github.com/supabase-community/supabase-kt/assets/43868345/33c995e8-0253-44a8-9044-b4d604881d07">
<img width="1154" alt="Screen Shot 2023-06-03 at 14 04 19" src="https://github.com/supabase-community/supabase-kt/assets/43868345/5add2d7c-7382-4f72-8483-65598c3e54db">

### ⚙️ Code to upload
```kotlin
  override suspend fun uploadImage(image: ByteArray) {
      storage["Product%20Image"].upload(
          "newimage.png", image,
          upsert = true
      )
  }
```

### 🎥 Video
I recorded the video and publish it in private mode to YouTube (size is quite big)
https://youtu.be/TdsjfhqTwls

### Steps To Reproduce (optional)

1. Upload an image with anh given name, let's say "new-image.png" with option upsert is true
2. Upload that image again with the same name, with upsert option is true

### Relevant log output (optional)

```shell
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.manageproducts, PID: 11067
    io.github.jan.supabase.exceptions.UnauthorizedRestException: Invalid JWT (new row violates row-level security policy (USING expression) for table "objects")
    URL: https://tyjxzodfrahibdkhgquy.supabase.co/storage/v1/object/Product%20Image/sdfsdfdfs.png
    Headers: [Authorization=[Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5anh6b2RmcmFoaWJka2hncXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODUxMTM2MDcsImV4cCI6MjAwMDY4OTYwN30.rXN-_rGEHKjOlo75xoDYOPkshrno9rK7h1H-CXFb2_g], x-upsert=[true], apikey=[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5anh6b2RmcmFoaWJka2hncXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODUxMTM2MDcsImV4cCI6MjAwMDY4OTYwN30.rXN-_rGEHKjOlo75xoDYOPkshrno9rK7h1H-CXFb2_g], Accept=[application/json], Accept-Charset=[UTF-8]]
    Http Method: POST
        at io.github.jan.supabase.storage.StorageImpl.parseErrorResponse(Storage.kt:270)
        at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:62)
        at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:62)
        at io.github.jan.supabase.network.SupabaseApi.rawRequest$suspendImpl(SupabaseApi.kt:25)
        at io.github.jan.supabase.network.SupabaseApi$rawRequest$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
        at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:345)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:135)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:109)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:59)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6921227, Dispatchers.Main.immediate]
```

**Comment by jan-tennert** [comment]
Do you have a policy for updating? Upsert may need a policy for that

**Comment by hieuwu** [comment]
I enabled UPDATE policy and it works. Thanks Jan.

<img width="1173" alt="Screen Shot 2023-06-05 at 11 29 07" src="https://github.com/supabase-community/supabase-kt/assets/43868345/28cea4e2-5a72-4aa4-aa31-4a556649d9a1">
