### ISSUE TITLE
[Bug]: Element class kotlinx.serialization.json.JsonLiteral is not a JsonArray

### ISSUE THREAD

**Issue by EBfVince** [supabase-community/supabase-kt#211]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

1.1.0-beta-2

### Target(s)

Android

### What happened? (include your code)

Each time I tried to call `client.postgrest["my-db].insert`, it ends with an Exception.

Here is the code I use.

```kotlin
client.postgrest["devices"].insert(buildJsonObject {
    put("name", device.name)
    put("fcm_token", device.fcmToken)
}).decodeSingle<Device>()
```

I successfully fetch data from my database, but impossible to insert values.

### Steps To Reproduce (optional)

1. Install the dependency `postgrest-kt` ([see here](https://supabase.com/docs/reference/kotlin/installing))
2. Insert data ([same as here](https://supabase.com/docs/reference/kotlin/insert))

### Relevant log output (optional)

```shell
java.lang.IllegalArgumentException: Element class kotlinx.serialization.json.JsonLiteral is not a JsonArray
                                                  	at kotlinx.serialization.json.JsonElementKt.error(JsonElement.kt:316)
                                                  	at kotlinx.serialization.json.JsonElementKt.getJsonArray(JsonElement.kt:245)
                                                  	at com.vinceglb.teleport.MainActivityKt$Content$1$1.invokeSuspend(MainActivity.kt:152)
                                                  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                  	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                  	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                  	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                  	at android.os.Handler.handleCallback(Handler.java:942)
                                                  	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                  	at android.os.Looper.loopOnce(Looper.java:201)
                                                  	at android.os.Looper.loop(Looper.java:288)
                                                  	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                  	at java.lang.reflect.Method.invoke(Native Method)
                                                  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                  	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@224b51c, androidx.compose.runtime.BroadcastFrameClock@877d525, StandaloneCoroutine{Cancelling}@d9536fa, AndroidUiDispatcher@ea4c4ab]
```

**Comment by jan-tennert** [comment]
Thank you for reporting this, should be fixed in [1.1.0-rc-1](https://github.com/supabase-community/supabase-kt/releases/tag/1.1.0-rc-1)! Let me know if there are any issues left!

**Comment by EBfVince** [comment]
Thanks a lot! It works great now!
