### ISSUE TITLE
[Bug]: Throwing err

### ISSUE THREAD

**Issue by yoobi** [supabase-community/supabase-kt#242]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

1.2.0

### Target(s)

Android

### What happened? (include your code)

When trying to connect to a stopped Supabase I get the following error:
```
Error while trying to connect to realtime websocket. Trying again in Infinity
io.ktor.client.call.NoTransformationFoundException: No transformation found: class io.ktor.utils.io.ByteBufferChannel -> class io.ktor.client.plugins.websocket.DefaultClientWebSocketSession
with response from wss://[TRUNCATED].net/realtime/v1/websocket?apikey=[TRUNCATED]-o&vsn=1.0.0:
status: 502 Bad Gateway
response headers: 
Date: Thu, 27 Jul 2023 15:21:34 GMT
, Content-Length: 11
, Content-Type: text/plain; charset=utf-8
	at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:93)
	at io.ktor.client.plugins.websocket.BuildersKt$webSocketSession$2.invokeSuspend(builders.kt:242)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

### Steps To Reproduce (optional)

1. Stop your Supabase
2. Try to connect to it

**Comment by jan-tennert** [comment]
What do you mean with "stopped supabase"?

**Comment by jan-tennert** [comment]
I'm not sure if I understand the problem, supabase shouldn't be down normally? If there was something wrong and the client disconnected, it should try to reconnect on its own.

**Comment by yoobi** [comment]
I meant that the errors log shouldn't be shown if the supabase server is down, you'll know it is down because when gettting `realtime.status` the status is `Realtime.Status.DISCONNECTED`

**Comment by jan-tennert** [comment]
I see what you mean, you can disable logging all along using this:
```kotlin
Logger.setLogWriters(emptyList())
```
This should make this log disappear.

**Comment by yoobi** [comment]
Okay thank you ! It did removed the logs
