### ISSUE TITLE
[Bug]: Illegal input: Failed resolution of: Ljava/time/Instant;

### ISSUE THREAD

**Issue by RamiBadyan** [supabase-community/supabase-kt#270]
### General Info

- [x] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

bom:1.2.0

### Target(s)

Android

### What happened? (include your code)

When trying to login on API 25 or lower an exception is thrown: 
"Exception: Illegal input: Failed resolution of: Ljava/time/Instant;"

And when trying again to log in another error appears like this:
"Exception: Illegal input: kotlinx.datetime.Instant"

I use io.ktor:ktor-client-cio:2.3.3

The code I used: 
`  viewModelScope.launch(Dispatchers.IO) {
            try {
                client.gotrue.loginWith(Email) {
                    email = _state.value.email
                    password = _state.value.password
                }
            } catch (e: Exception) {
                Log.d(tag, "Exception: ${e.message}")
            }
        }`

### Relevant log output (optional)

```shell
io.ktor.serialization.JsonConvertException: Illegal input: Failed resolution of: Ljava/time/Instant;
                                                                                                    	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:90)
                                                                                                    	at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1$2.emit(Emitters.kt:224)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
                                                                                                    	at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1.collect(SafeCollector.common.kt:113)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ReduceKt.firstOrNull(Reduce.kt:243)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt.firstOrNull(Unknown Source)
                                                                                                    	at io.ktor.serialization.ContentConverterKt.deserialize(ContentConverter.kt:123)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation.convertResponse$ktor_client_content_negotiation(ContentNegotiation.kt:230)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invokeSuspend(ContentNegotiation.kt:262)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(ContentNegotiation.kt)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(ContentNegotiation.kt)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
                                                                                                    	at io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:177)
                                                                                                    	at io.ktor.client.HttpClient$4.invoke(HttpClient.kt)
                                                                                                    	at io.ktor.client.HttpClient$4.invoke(HttpClient.kt)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:142)
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
                                                                                                    	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
                                                                                                    	at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:88)
                                                                                                    	at io.github.jan.supabase.gotrue.providers.builtin.DefaultAuthProvider$DefaultImpls.login(DefaultAuthProvider.kt:125)
                                                                                                    	at io.github.jan.supabase.gotrue.providers.builtin.DefaultAuthProvider$login$1.invokeSuspend(DefaultAuthProvider.kt)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7c86a4c, Dispatchers.IO]
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
                                                                                                    	at kotlinx.datetime.Instant.<clinit>(Instant.kt:96)
                                                                                                    	at kotlinx.datetime.serializers.InstantIso8601Serializer.deserialize(InstantSerializers.kt:27)
                                                                                                    	at kotlinx.datetime.serializers.InstantIso8601Serializer.deserialize(InstantSerializers.kt:21)
2023-08-27 14:34:04.614  8843-8898  AndroidRuntime   
                    E  	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
                                                                                                    	at io.github.jan.supabase.gotrue.user.UserInfo$$serializer.deserialize(UserInfo.kt:9)
                                                                                                    	at io.github.jan.supabase.gotrue.user.UserInfo$$serializer.deserialize(UserInfo.kt:9)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
                                                                                                    	at io.github.jan.supabase.gotrue.user.UserSession$$serializer.deserialize(UserSession.kt:10)
                                                                                                    	at io.github.jan.supabase.gotrue.user.UserSession$$serializer.deserialize(UserSession.kt:10)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
                                                                                                    	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
                                                                                                    	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:82)
                                                                                                    	... 36 more
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Instant" on path: DexPathList[[zip file "/data/app/org.example-2/base.apk"],nativeLibraryDirectories=[/data/app/org.example-2/lib/x86, /system/lib, /vendor/lib]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	... 52 more
```

**Comment by jan-tennert** [comment]
java.time.Instant requires Api 26 or higher, I suppose thats why this error is there. KotlinX Datetime probably requires java.time.Instant so I don't know if there is a way to make this run on API 25 or lower

**Comment by RamiBadyan** [comment]
So is there any solution?

**Comment by jan-tennert** [comment]
I don't think so, I assume using sdk 26+ works?

**Comment by RamiBadyan** [comment]
Well, I guess I have to update my app to run on sdk 26+.

**Comment by florian-mlr** [comment]
Did you try desugaring ? I haven't tried it yet but maybe it can help
https://github.com/Kotlin/kotlinx-datetime#using-in-your-projects
https://developer.android.com/studio/write/java8-support#library-desugaring

**Comment by RamiBadyan** [comment]
**That is great!** It worked when adding this line: 
`coreLibraryDesugaringEnabled true` 
in `build.gradle` file -> `compileOptions`

Thank you florian-mlr
