### ISSUE TITLE
[Bug]: java.lang.IllegalStateException: Plugin rest not installed or not of type class io.github.jan.supabase.postgrest.Postgrest

### ISSUE THREAD

**Issue by iMonZ** [supabase-community/supabase-kt#28]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

When I run the insert command:

```
override fun OnReceive(context:Context, intent: Intent?) {
   GlobalScope.launch { sendTheTextMessage(sender = messageSender, message = messageContent, date = messageDate, receiver = messageReceiver )  }
}
```

```
suspend fun sendTheTextMessage(sender: String, message: String, date: String, receiver: String){


       client.postgrest["text_messages"]
         .insert(Message(sender, message))
}
```

### Platform(s)

Android

### Relevant log output

```shell
java.lang.IllegalStateException: Plugin rest not installed or not of type class io.github.jan.supabase.postgrest.Postgrest
at io.github.jan.supabase.postgrest.PostgrestKt.getPostgrest(Postgrest.kt:92)
                                                                                                    	at com.nougatbits.nougatbitssmspushservice.MessageReceiverKt.sendTheTextMessage(MessageReceiver.kt:98)
                                                                                                    	at com.nougatbits.nougatbitssmspushservice.MessageReceiver$onReceive$1.invokeSuspend(MessageReceiver.kt:70)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@33d62d8, Dispatchers.Default]
```

**Comment by jan-tennert** [comment]
You have to install the Postgrest plugin your supabase client https://github.com/supabase-community/supabase-kt/wiki/Postgrest#installation

**Comment by iMonZ** [comment]
> https://github.com/supabase-community/supabase-kt/wiki/Postgrest#installation

Thanks, that was it. At least I get now a different error 
`    kotlinx.serialization.SerializationException: Serializer for class 'Message' is not found.`

**Comment by jan-tennert** [comment]
> > https://github.com/supabase-community/supabase-kt/wiki/Postgrest#installation
> 
> Thanks, that was it. At least I get now a different error ` kotlinx.serialization.SerializationException: Serializer for class 'Message' is not found.`

yep for that you can look at https://github.com/Kotlin/kotlinx.serialization#introduction-and-references

**Comment by iMonZ** [comment]
> > > https://github.com/supabase-community/supabase-kt/wiki/Postgrest#installation
> > 
> > 
> > Thanks, that was it. At least I get now a different error ` kotlinx.serialization.SerializationException: Serializer for class 'Message' is not found.`
> 
> yep for that you can look at https://github.com/Kotlin/kotlinx.serialization#introduction-and-references

Thank you so much! You helped me a lot.
And also thanks for this module

But... kotlinx.serialization compiler plugin is not applied to the module, so this annotation would not be processed. Make sure that you've setup your buildscript correctly and re-import project.

**Comment by jan-tennert** [comment]
You have to apply the serialization plugin to your project to make it work
