### ISSUE TITLE
[Bug]: Crash when using compose-auth on Android 14

### ISSUE THREAD

**Issue by fan123199** [supabase-community/supabase-kt#318]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

1.4.2

### Target(s)

Android

### What happened? (include your code)

A bug happened!
```
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Landroid/os/Bundle;Landroid/os/Bundle;ZZLjava/util/Set;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Landroidx/credentials/GetCustomCredentialOption; or its super classes (declaration of 'androidx.credentials.GetCustomCredentialOption' appears in /data/app/~~l7rse9SBOzOeUW-V5EndvA==/im.xx.xx-wh3kGiDz54c8DyrtbJbh0A==/base.apk)
                                      	at com.google.android.libraries.identity.googleid.GetGoogleIdOption.<init>(com.google.android.libraries.identity.googleid:googleid@@1.1.0:3)
                                      	at com.google.android.libraries.identity.googleid.GetGoogleIdOption$Builder.build(com.google.android.libraries.identity.googleid:googleid@@1.1.0:1)
                                      	at io.github.jan.supabase.compose.auth.UtilsKt.getGoogleIDOptions(Utils.kt:35)
                                      	at io.github.jan.supabase.compose.auth.composable.GoogleAuthKt$signInWithCM$1.invokeSuspend(GoogleAuth.kt:63)
                                      	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                      	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                      	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                      	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                      	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                      	at android.os.Handler.handleCallback(Handler.java:958)
                                      	at android.os.Handler.dispatchMessage(Handler.java:99)
                                      	at android.os.Looper.loopOnce(Looper.java:205)
                                      	at android.os.Looper.loop(Looper.java:294)
                                      	at android.app.ActivityThread.main(ActivityThread.java:8171)
                                      	at java.lang.reflect.Method.invoke(Native Method)
                                      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                      	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@93eddf1, androidx.compose.runtime.BroadcastFrameClock@ca1dd6, StandaloneCoroutine{Cancelling}@4aa1857, AndroidUiDispatcher@a210f44]
```

```kotlin
//build.gradle
    implementation(platform("io.github.jan-tennert.supabase:bom:1.4.2"))
    implementation("io.github.jan-tennert.supabase:postgrest-kt")
    implementation("io.github.jan-tennert.supabase:compose-auth")
    implementation("io.github.jan-tennert.supabase:compose-auth-ui")


//supabaseClient
val client: SupabaseClient = createSupabaseClient(
            supabaseUrl = "xxxx",
            supabaseKey = "xxxxx"
        ) {
            install(Postgrest)
            install(GoTrue)
            install(ComposeAuth) {
                googleNativeLogin("xxxx")
            }
        }

//usage
@Composable
fun LoginScreen(loginViewModel: LoginViewModel = hiltViewModel()) {
    val authState = loginViewModel.supabaseClient.composeAuth.rememberLoginWithGoogle(
        onResult = {
            when (it) { //handle errors
                NativeSignInResult.ClosedByUser -> {}
                is NativeSignInResult.Error -> {}
                is NativeSignInResult.NetworkError -> {}
                NativeSignInResult.Success -> {}
            }
        }
    )

OutlinedButton(
            onClick = {
                authState.startFlow()
            }, //Login with Google,
            content = { ProviderButtonContent(Google, "Sign in with Google") },
            modifier = Modifier.align(Alignment.Center)
        )
}
```

And run debug on Google Pixel 6 Pro with Android 14.  Crashed when just come into login Screen, not even click sign in button

**Comment by fan123199** [comment]
And I found some related info from android dev official [HERE](https://developer.android.com/jetpack/androidx/releases/credentials#version_10_2)

```
Note: In general, you should use the [latest version of androidx.credentials](https://developer.android.com/jetpack/androidx/releases/credentials#latest). For projects still using 1.0 versions:

Android 14 requires androidx.credentials versions 1.0.0-alpha07 or higher. Earlier versions of androidx.credentials will throw an exception UnsupportedOperationException("Post-U not supported yet") when run on Android 14.
Android versions up to 13 should use androidx.credentials version 1.0.0-alpha06 or lower.
```

**Comment by jan-tennert** [comment]
> And I found some related info from android dev official [HERE](https://developer.android.com/jetpack/androidx/releases/credentials#version_10_2)
> 
> > Note: In general, you should use the [latest version of androidx.credentials](https://developer.android.com/jetpack/androidx/releases/credentials#latest). For projects still using 1.0 versions:
> > Android 14 requires androidx.credentials versions 1.0.0-alpha07 or higher. Earlier versions of androidx.credentials will throw an exception UnsupportedOperationException("Post-U not supported yet") when run on Android 14.
> > Android versions up to 13 should use androidx.credentials version 1.0.0-alpha06 or lower.

Hey, thank you for reporting this! I'm publishing version `1.4.3` which uses Google OneTap on Android 14 for now. Will re-integrate the CM implementation in 1.5.x
