### ISSUE TITLE
[Bug]: Email OTP not working over CLI

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [supabase-community/supabase-kt#331]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

1.4.4

### Target(s)

Android

### What happened? (include your code)

I am using Supabase CLI to develop locally, and while using the following code to verify the user:
```kotlin
gotrue.resendEmail(OtpType.Email.SIGNUP, email)
```

I get the following error:
```
For security purposes, you can only request this once every 0 seconds.
                 URL: http://192.168.1.46:54321/auth/v1/resend
                 Headers: [Authorization=[Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0], apikey=[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0], X-Client-Info=[supabase-kt/1.4.4], Accept=[application/json], Accept-Charset=[UTF-8]]
                 Http Method: POST
                 io.github.jan.supabase.exceptions.UnknownRestException: For security purposes, you can only request this once every 0 seconds.
                 URL: http://192.168.1.46:54321/auth/v1/resend
                 Headers: [Authorization=[Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0], apikey=[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0], X-Client-Info=[supabase-kt/1.4.4], Accept=[application/json], Accept-Charset=[UTF-8]]
                 Http Method: POST
                 	at io.github.jan.supabase.gotrue.GoTrueImpl.parseErrorResponse(GoTrueImpl.kt:479)
                 	at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:62)
                 	at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:62)
                 	at io.github.jan.supabase.network.SupabaseApi.rawRequest$suspendImpl(SupabaseApi.kt:25)
                 	at io.github.jan.supabase.network.SupabaseApi$rawRequest$1.invokeSuspend(Unknown Source:15)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

I get this exact same error when using:
```kotlin
authenticator.sendOtpTo(Email) {
    this.email = email
    this.password = password
}
```

Is this a known issue? Do we have a workaround for it?

**Comment by shubhamsinghshubham777** [comment]
It was my bad, I observed that I was already using the following code to register the user:
```kotlin
gotrue.signUpWith(Email) {
    this.email = email
    this.password = password
}
```
And this logic already sends a verification E-mail (I found it once I checked my local InBucket instance)

Since I had called `resendEmail` and `sendOtpTo` functions just after the `signUpWith` function, therefore it showed the error mentioned above.

This issue is resolved from my end, hence closing it ✅
