### ISSUE TITLE
[Question]: GoTrueMock for testing implementation

### ISSUE THREAD

**Issue by tschuehly** [supabase-community/supabase-kt#362]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

I'm trying to test my [htmx-spring-supabase-auth](https://github.com/tschuehly/htmx-spring-supabase-auth) library after migrating to supabase-kt from gotrue-kt

I'm using the same [GoTrueMock](https://github.com/tschuehly/htmx-spring-supabase-auth/blob/be9938ca48456113a537f6fc72818f3408a49834/src/test/kotlin/de/tschuehly/htmx/spring/supabase/auth/test/mock/GoTrueMock.kt) as you do in your library tests.

I wanted to know why this mock returns a different response message than the official supabase API. For example when sending a wrong password the official supabase API returns "Invalid login credentials"

I'm using the response messages from supabase in my [ExceptionHandler](https://github.com/tschuehly/htmx-spring-supabase-auth/blob/be9938ca48456113a537f6fc72818f3408a49834/src/main/kotlin/de/tschuehly/htmx/spring/supabase/auth/service/SupabaseUserServiceGoTrueImpl.kt#L158) now I'm debating whether this is a good idea or is there a better way to that?

What do you think? Should I change the mock to match my expectations :thinking: ?

**Comment by jan-tennert** [comment]
> ### General info
> 
>     * [x]  I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
> 
> 
> ### What is your question?
> 
> I'm trying to test my [htmx-spring-supabase-auth](https://github.com/tschuehly/htmx-spring-supabase-auth) library after migrating to supabase-kt from gotrue-kt
> 
> I'm using the same [GoTrueMock](https://github.com/tschuehly/htmx-spring-supabase-auth/blob/be9938ca48456113a537f6fc72818f3408a49834/src/test/kotlin/de/tschuehly/htmx/spring/supabase/auth/test/mock/GoTrueMock.kt) as you do in your library tests.
> 
> I wanted to know why this mock returns a different response message than the official supabase API. For example when sending a wrong password the official supabase API returns "Invalid login credentials"
> 
> I'm using the response messages from supabase in my [ExceptionHandler](https://github.com/tschuehly/htmx-spring-supabase-auth/blob/be9938ca48456113a537f6fc72818f3408a49834/src/main/kotlin/de/tschuehly/htmx/spring/supabase/auth/service/SupabaseUserServiceGoTrueImpl.kt#L158) now I'm debating whether this is a good idea or is there a better way to that?
> 
> What do you think? Should I change the mock to match my expectations 🤔 ?

Hey, for the GoTrue tests the response messages weren't really important as the library doesn't do anything with the messages itself. (It just checks the response code, headers and decodes potential error responses). I think you should be fine by just changing the mock. I'll say that the current Mock is not the best solution and might need some refactoring.

**Comment by jan-tennert** [comment]
@tschuehly Did this answer your question?

**Comment by tschuehly** [comment]
Hey @jan-tennert, I've wanted to upgrade my libary to the newest version but it seems like you removed the mock. How do you test it now?
I currently get this error in production,  do you think this could be caused by a change happening from v2.0.4?

It seems to happen here: https://github.com/tschuehly/htmx-supabase-spring-boot-starter/blob/12f52b366d780b0ef73e16fb319154878065066f/src/main/kotlin/de/tschuehly/htmx/spring/supabase/auth/service/SupabaseUserServiceGoTrueImpl.kt#L68

```
io.github.jan.supabase.exceptions.HttpRequestException: HTTP request to http://localhost (POST) failed with message: 
        at io.github.jan.supabase.network.KtorSupabaseHttpClient.request(KtorSupabaseHttpClient.kt:55) ~[supabase-kt-jvm-2.0.4.jar:na]
        at io.github.jan.supabase.network.KtorSupabaseHttpClient$request$1.invokeSuspend(KtorSupabaseHttpClient.kt) ~[supabase-kt-jvm-2.0.4.jar:na]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.9.24.jar:1.9.24-release-822]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
        at de.tschuehly.htmx.spring.supabase.auth.service.SupabaseUserServiceGoTrueImpl.runGoTrue(SupabaseUserServiceGoTrueImpl.kt:149) ~[htmx-supabase-spring-boot-starter-0.3.4.jar:na]
        at de.tschuehly.htmx.spring.supabase.auth.service.SupabaseUserServiceGoTrueImpl.runGoTrue$default(SupabaseUserServiceGoTrueImpl.kt:144) ~[htmx-supabase-spring-boot-starter-0.3.4.jar:na]
        at de.tschuehly.htmx.spring.supabase.auth.service.SupabaseUserServiceGoTrueImpl.sendOtp(SupabaseUserServiceGoTrueImpl.kt:67) ~[htmx-supabase-spring-boot-starter-0.3.4.jar:na]
        at de.tschuehly.htmx.spring.supabase.auth.controller.SupabaseUserController.sendEmailOtp(SupabaseUserController.kt:52) ~[htmx-supabase-spring-boot-starter-0.3.4.jar:na]
        
```

**Comment by jan-tennert** [comment]
> I've wanted to upgrade my libary to the newest version but it seems like you removed the mock. How do you test it now?

There have been a few changes to simplify the testing. All modules implement the testing module which provides a function to create a [mocked supabase client](https://github.com/supabase-community/supabase-kt/blob/master/test-common/src/commonMain/kotlin/io/github/jan/supabase/testing/SupabaseClientMock.kt), which is created [per-test](https://github.com/supabase-community/supabase-kt/blob/a07783f64cdbbf1cf00e7cceb73289b2778424b1/GoTrue/src/commonTest/kotlin/AuthApiTest.kt#L46).
>  I currently get this error in production, do you think this could be caused by a change happening from v2.0.4?

Well, I couldn't say exactly as the version `2.0.4` you are using is already pretty old, but in the past connections to `localhost` happened because of coroutine issues, which were pretty hard to identify. Is this the full stacktrace? In any case, updating the library and therefore ktor could solve this.

**Comment by jan-tennert** [comment]
Also, the old mock can probably still be used.

**Comment by tschuehly** [comment]
Thanks for the quick reply, just pushed the update to prod. I will report back if the error occurs again. Is there any way to use the libary with blocking calls instead of coroutines? Currently I need to wrap everything in a runBlocking scope

**Comment by jan-tennert** [comment]
> I will report back if the error occurs again. Is there any way to use the libary with blocking calls instead of coroutines? Currently I need to wrap everything in a runBlocking scope

No, that is not possible.
