### ISSUE TITLE
[Question]: How to clear user cache when user doesn't exist anymore ?

### ISSUE THREAD

**Issue by florian-mlr** [supabase-community/supabase-kt#363]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

Hello, I have a specific use case. After deleting a user (by calling my custom edge function), I want to logout however the logout method return `User not found`

```
io.github.jan.supabase.exceptions.UnknownRestException: User not found
URL: https://***********.supabase.co/auth/v1/logout?scope=local
                                                                                                    
Http Method: POST
at io.github.jan.supabase.gotrue.GoTrueImpl.parseErrorResponse(GoTrueImpl.kt:479)
at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:62)
at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:62)
at io.github.jan.supabase.network.SupabaseApi.rawRequest$suspendImpl(SupabaseApi.kt:25)
at io.github.jan.supabase.network.SupabaseApi$rawRequest$1.invokeSuspend(Unknown Source:15)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:347)
at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:135)
at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:109)
at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:59)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7918)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

However when I call `client.gotrue.currentSessionOrNull()` it still return the user, looks like the user cache is not cleared, how can i clear it ?

**Comment by jan-tennert** [comment]
You can use [`GoTrue#clearSession`](https://github.com/supabase-community/supabase-kt/blob/7ea195fa33664cd0091d18854609bb7173b06802/GoTrue/src/commonMain/kotlin/io/github/jan/supabase/gotrue/GoTrue.kt#L309)

**Comment by florian-mlr** [comment]
> You can use [`GoTrue#clearSession`](https://github.com/supabase-community/supabase-kt/blob/7ea195fa33664cd0091d18854609bb7173b06802/GoTrue/src/commonMain/kotlin/io/github/jan/supabase/gotrue/GoTrue.kt#L309)

Yes it works ! Thank you for your reactivity
