### ISSUE TITLE
[Bug]: Upload a file from Uri on Android crashes since 2.X versions

### ISSUE THREAD

**Issue by vinceglb** [supabase-community/supabase-kt#370]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.0.0-alpha-1, 2.0.0-alpha-2, 2.0.0-beta-1

### Target(s)

Android

### What happened? (include your code)

I used Storage with Supabase 1.4.7 version, and I was able to upload files from Android Uri to Supabase.
I upgraded to 2.0.0-beta-1 and suddenly, it starts crashing on Android.

Here is the code:

```kotlin
val uri = ...
val bucketApi = supabase.storage["bug"]
coroutineScope.launch {
   bucketApi.upload(
      path = "androidCrash",
      uri = uri,
      upsert = true
   )
}
```

Uploading the same file by converting the Uri to bytes works well.

```kotlin
// Get bytes from uri
val bytes = context.contentResolver.openInputStream(uri)?.use {
   it.buffered().readBytes()
} ?: return@FilePicker

// Upload
val bucketApi = supabase.storage["bug"]
coroutineScope.launch {
   bucketApi.upload(
      path = "androidCrash",
      data = bytes,
      upsert = true
   )
}
```

### Steps To Reproduce (optional)

Reproduce the bug by using this repository:
https://github.com/vinceglb/SupabaseBugReport

### Relevant log output (optional)

```shell
FATAL EXCEPTION: main
Process: com.vinceglb.temp, PID: 10998
io.github.jan.supabase.exceptions.HttpRequestException: HTTP request to http://localhost (POST) failed with message: Stream Closed
at io.github.jan.supabase.network.KtorSupabaseHttpClient.request(KtorSupabaseHttpClient.kt:55)
at io.github.jan.supabase.network.KtorSupabaseHttpClient$request$1.invokeSuspend(Unknown Source:15)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:233)
at android.os.Looper.loop(Looper.java:344)
at android.app.ActivityThread.main(ActivityThread.java:8248)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@a03b1de, androidx.compose.runtime.BroadcastFrameClock@3788fbf, StandaloneCoroutine{Cancelling}@2db968c, AndroidUiDispatcher@ba5f1d5]
```

**Comment by jan-tennert** [comment]
Thank you for reporting this! Found the issue, will be fixed in the next beta version!
