### ISSUE TITLE
[Bug]: HTTPS is used implicitly instead of specified HTTP URL

### ISSUE THREAD

**Issue by profiluefter** [supabase-community/supabase-kt#40]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

I specified a HTTP supabase url and the request got made using HTTPS.
I'm using the Supabase CLI for testing so this is a relevant use case for HTTP. (also selfhosted deployments would be another)

Setting a customUrl for the Postgrest plugin is my current working workaround for this:
```java
install(Postgrest) {
    customUrl = "http://x.x.x.x:54321/rest/v1/"
}
```

The supabase-py project handles this case by printing a warning message if HTTP is used.

### Platform(s)

Android

### Relevant log output

```shell
Caused by: io.github.jan.supabase.exceptions.HttpRequestException: HTTP request to http://localhost?select=%2A (GET) failed with message: Invalid TLS record type code: 72
    at io.github.jan.supabase.network.KtorSupabaseHttpClient.request(KtorSupabaseHttpClient.kt:46)
    at io.github.jan.supabase.network.KtorSupabaseHttpClient$request$1.invokeSuspend(Unknown Source:15)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by profiluefter** [comment]
Just found out about the `useHTTPS` property of the builder which is the proper way to disabled this.
I'm not a huge fan of this system. Can we default to https if no protocol is specified (although that should be an invalid parameter imho) but keep HTTP if that's specified?

Great library btw! I'm just migrating a project of mine to this from [my own attempt at building supabase-kt](https://github.com/profiluefter/supabase-kt).

**Comment by jan-tennert** [comment]
Thanks! Yea the protocols are getting removed in the SupabaseClient, but I can definitely change the useHTTPS property automatically depending on what's in the supabase url in the Builder.

**Comment by profiluefter** [comment]
An additional suggestion that I noticed just now: Can this be integrated with the realtime plugin to automatically set the `secure` property of the websocket?

**Comment by jan-tennert** [comment]
If the supabaseUrl uses an HTTP(s) connection? Or when useHTTPS is true/false?

**Comment by profiluefter** [comment]
I would use the global useHTTPS value as default and thanks to your change just now it'd also be set based on the url, right?

**Comment by jan-tennert** [comment]
yes, it just checks whether the supabaseUrl starts with http else it uses https

**Comment by profiluefter** [comment]
Thanks a lot!
