### ISSUE TITLE
[Bug]: headers must have required property 'authorization'

### ISSUE THREAD

**Issue by denchic45** [supabase-community/supabase-kt#44]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

I was trying to get a list of files in a folder, but it requires 'authorization' in the header. There is only apiKey.

request:
```kotlin
val items = storage["mybucket"].list("courses")
```
client:
```kotlin
createSupabaseClient(
            supabaseUrl = SupabaseConstants.url,
            supabaseKey = SupabaseConstants.key
        ) {
            install(Realtime)
            install(Storage)
        }
```

### Platform(s)

Desktop

### Relevant log output

```shell
Error :(headers must have required property 'authorization')
URL: https://***.supabase.co/storage/v1/object/list/mybucket
Headers: [apikey=[***], Accept=[application/json], Accept-Charset=[UTF-8]]
Http Method: POST
io.github.jan.supabase.exceptions.BadRequestRestException: Error :(headers must have required property 'authorization')
URL: https://***.supabase.co/storage/v1/object/list/mybucket
Headers: [apikey=[***], Accept=[application/json], Accept-Charset=[UTF-8]]
Http Method: POST
	at app//io.github.jan.supabase.storage.StorageImpl.parseErrorResponse(Storage.kt:140)
	at app//io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:38)
	at app//io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:38)
	at app//io.github.jan.supabase.network.SupabaseApi.request$suspendImpl(SupabaseApi.kt:17)
	at app//io.github.jan.supabase.network.SupabaseApi$request$1.invokeSuspend(SupabaseApi.kt)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at app//kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at app//kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by denchic45** [comment]
I'm currently solving this by adding a header in the client's http config
```
createSupabaseClient(
            supabaseUrl = SupabaseConstants.url,
            supabaseKey = SupabaseConstants.key
        ) {
            httpConfig {
                install(DefaultRequest) {
                    header("authorization", "Bearer ${SupabaseConstants.key}")
                }
            }

            install(Realtime)
            install(Storage)
        }
```

**Comment by jan-tennert** [comment]
Yea the authorization header only gets added when using the GoTrue plugin, I suppose you are not using any authentication so you can use this:

```kotlin
val client = createSupabaseClient(url, key) {

install(GoTrue) {
    autoLoadFromStorage = false
    alwaysAutoRefresh = false
}
...

}
client.gotrue.importAuthToken(key)
```
