### ISSUE TITLE
Add goTrue signing in/up Support For Android Version 7 and below [Feature request]: 

### ISSUE THREAD

**Issue by kibitheM** [supabase-community/supabase-kt#440]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

Hello... I noticed that the library (goTrue) only support signing in/signing up from android Api 26 and above. That is from android 8 and above. I have tried signing in/up with an android 7 device and an android 5.1 device and i get the same error in both. I think the error mainly comes from how the date/time instant of UserSession and UserInfo has been implemeted..there is no backward support for older versions of android/ from api 26 and below. Android 5 - 7 pretty makes the mojority of android devices out there and it will be such a great help to us (and especially me right now) if this amazing library can support them sooner rather than later. Having said that iam no expert in this and am not sure even if maybe there was something i needed to do on my side to support these versions codewise, all i have done is to stick to the documentation. Thank you once again for such a great and amazing library. Below is the sample of the error iam getting on these devices

> java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
                 	>at kotlinx.datetime.Instant.<clinit>(Instant.kt:96)
                 	>at kotlinx.datetime.serializers.InstantIso8601Serializer.deserialize(InstantSerializers.kt:27)
                 	>at kotlinx.datetime.serializers.InstantIso8601Serializer.deserialize(InstantSerializers.kt:21)
                 	>at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)
                 	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52)
                 	>at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
                 	>at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:288)
                 	>at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:294)
                 	>at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:286)
                 	>at io.github.jan.supabase.gotrue.user.UserInfo$$serializer.deserialize(UserInfo.kt:9)
                 	>at io.github.jan.supabase.gotrue.user.UserInfo$$serializer.deserialize(UserInfo.kt:9)
                 	>at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)
                 	>at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52)
                 	>at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
                 	>at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:288)
                 	>at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:294)
                 	>at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:286)
                 	>at io.github.jan.supabase.gotrue.user.UserSession$$serializer.deserialize(UserSession.kt:10)
                 	>at io.github.jan.supabase.gotrue.user.UserSession$$serializer.deserialize(UserSession.kt:10)
                 	>at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)

### Usecase

Sign in Sign Up for older versions of android devices that is 7 and below.

**Comment by jan-tennert** [comment]
You might have to use library desugaring as KotlinX Datetime suggests:
> If you target Android devices running below API 26, you need to use Android Gradle plugin 4.0 or newer and enable [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring).
This should enable you to use this library on older Android versions

**Comment by kibitheM** [comment]
Thank you very much. Iam glad I can use this library with any version of android. This was what I was looking for. Thank you once again.

**Comment by kibitheM** [comment]
> > Thank you very much. Iam glad I can use this library with any version of android. This was what I was looking for. Thank you once again.
> 
> Great, let me know if it works!

sure, I will
