### ISSUE TITLE
[Bug]: The app crashes when it performs a refresh token operation.

### ISSUE THREAD

**Issue by RamiBadyan** [supabase-community/supabase-kt#464]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

bom:2.1.3

### Target(s)

Android

When I use the app for about an hour and I refresh token, whether manually or automatically, the app crashes immediately.
This issue happened to me several times.

`D  Request failed with Connect timeout has expired [url=https://example.com/auth/v1/token?grant_type=refresh_token, connect_timeout=unknown ms]
E  FATAL EXCEPTION: main
   Process: com.otakio, PID: 17825
   io.github.jan.supabase.exceptions.HttpRequestException: HTTP request to http://localhost (POST) failed with message: Connect timeout has expired [url=https://example.com/auth/v1/token?grant_type=refresh_token, connect_timeout=unknown ms]
      at io.github.jan.supabase.network.KtorSupabaseHttpClient.request(KtorSupabaseHttpClient.kt:55)
      at io.github.jan.supabase.network.KtorSupabaseHttpClient$request$1.invokeSuspend(Unknown Source:15)
      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
      at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
      at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:347)
      at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
      at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:11)
      at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:55)
      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
      at android.os.Handler.handleCallback(Handler.java:958)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loopOnce(Looper.java:205)
      at android.os.Looper.loop(Looper.java:294)
      at android.app.ActivityThread.main(ActivityThread.java:8177)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
      Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c58efa4, Dispatchers.Main.immediate]`

**Comment by jan-tennert** [comment]
So what exactly do you call? The app shouldn't crash for automatic refreshes, as all exceptions are catched anyway. For the exception, this just looks like a timeout.

**Comment by RamiBadyan** [comment]
When I want to refresh the token, I use this code:
`
client.auth.refreshCurrentSession()
client.auth.retrieveUserForCurrentSession(updateSession = true)
` 
Is there any Problem with my code?

**Comment by jan-tennert** [comment]
Not really, but why do you want to refresh the session yourself?

**Comment by RamiBadyan** [comment]
Sometimes the token is not refreshed automatically, so I refresh it myself.
For example, if the token expires after an hour and I use the app for an hour, the token expires and a timeout error appears in all requests, so I need to refresh it myself.

**Comment by RamiBadyan** [comment]
I changed the validity period of the token to be valid for a week and not an hour and the issue seems to have been resolved.
Additionally, I now refresh the token when I start the app.

Since the issue is solved, I will close it.
