### ISSUE TITLE
[Question]:  Error when accessing storage bucket from kotlin sdk

### ISSUE THREAD

**Issue by lspradeep** [supabase-community/supabase-kt#515]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.2.0, 2.2.1

### Target(s)

JVM

### What happened? (include your code)

Account with Full Access is unable to access the storage bucket. Please! fix soon.

This is similar to this bug https://github.com/orgs/supabase/discussions/13344 , But in Supabase Kt sdk

io.github.jan.supabase.exceptions.UnknownRestException: new row violates row-level security policy
URL: https://wcehxxftdzipzmmeyhxi.supabase.co/storage/v1/object/storyimages/story_1710174855087.jpeg
Headers: [Authorization=[Bearer access-token], x-upsert=[false], apikey=api-key, X-Client-Info=[supabase-kt/2.2.0], Accept=[application/json], Accept-Charset=[UTF-8]]
Http Method: POST
	at io.github.jan.supabase.storage.StorageImpl.parseErrorResponse(Storage.kt:259)
	at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:58)
	at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:58)
	at io.github.jan.supabase.network.SupabaseApi.rawRequest$suspendImpl(SupabaseApi.kt:25)
	at io.github.jan.supabase.network.SupabaseApi$rawRequest$1.invokeSuspend(SupabaseApi.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:343)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:135)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:109)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-03-11 22:04:29.143 [eventLoopGroupProxy-4-2] TRACE i.k.s.p.c.ContentNegotiation - Skipping response body transformation from HttpStatusCode to OutgoingContent for the GET /bot6 request because the HttpStatusCode type is ignored. See [ContentNegotiationConfig::ignoreType].

**Comment by jan-tennert** [comment]
If you are actually signed in with a user, then something is wrong with your policy. Do you have any policies for this bucket?

**Comment by lspradeep** [comment]
Yes, I gave INSERT, SELECT, UPDATE, DELETE access for this user. Then i also tried  removing all the policies. Still getting the same error.

**Comment by jan-tennert** [comment]
Removing them doesn't help, then all requests get blocked. Can you share your policies?

**Comment by jan-tennert** [comment]
Also, you are definitely signed in when trying to upload? You can check by adding this before uploading:
```kotlin
println(supabase.auth.currentSessionOrNull)
```

**Comment by lspradeep** [comment]
double-checked everything, and I can assure you that I'm signed in.
I also verified the JWT that's passing in header

```
            println(SupabaseAdmin.supabaseClient.auth.currentSessionOrNull()?.accessToken)
            println(SupabaseAdmin.supabaseClient.auth.currentSessionOrNull()?.user?.email)
            val imageBlobNameUrlPair = myStorage.uploadFileToBucket(imageUrl)
```

Below image [all the policies]  
<img width="1324" alt="image" src="https://github.com/supabase-community/supabase-kt/assets/25198507/e9a681a8-7284-485c-b488-e533da8368dc">

Below image [user id that I use]  
<img width="705" alt="image" src="https://github.com/supabase-community/supabase-kt/assets/25198507/38872b62-63f7-46ce-b75b-6ce3a70363bb">

Below image [insert access for a particular user (admin) ]  
in place if _xyx_, actual user id comes
<img width="1324" alt="image" src="https://github.com/supabase-community/supabase-kt/assets/25198507/620c72b1-59bf-44a1-b82b-be23e9d4ea27">

**Comment by lspradeep** [comment]
I left these two blank. could that be an issue?

<img width="1322" alt="Screenshot 2024-03-12 at 9 28 26 AM" src="https://github.com/supabase-community/supabase-kt/assets/25198507/cd5249d6-9076-435f-944f-72a3e0548784">

**Comment by lspradeep** [comment]
My bad. It turns out the missing policies in the last image is the issue. After adding those it worked. Thank you.
