### ISSUE TITLE
[Question]: Is it really necessary that if the authentication with the keys is incorrect it will exit the application with a FATAL ERROR?

### ISSUE THREAD

**Issue by jeluchu** [supabase-community/supabase-kt#550]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.MD) page for similar problems

### What is your question?

I mean, I understand that if the credentials are not correct, the service should not accept requests, but instead of the app closing completely, wouldn't it be better to return an error indicating that they are invalid and not load anything requested from the service?

This is more than anything, in case an app, in case the key is not properly authenticated, wants to display an error message in the app, and not to close completely, maybe my point of view is wrong, but I would like to know if there is a way to avoid this behavior (ie, to close the app completely), so that in case of invalid authentication, directly those requests that are made return an informative error without returning the corresponding information from the service.

### Relevant log output (optional)

```shell
FATAL EXCEPTION: main                                                                                         Process: com.example.manageproducts, PID: 6141
io.github.jan.supabase.exceptions.UnauthorizedRestException: Invalid authentication credentials
Http Method: GET
at io.github.jan.supabase.postgrest.PostgrestImpl.parseErrorResponse(PostgrestImpl.kt:47)
at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:58)
at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:58)
at io.github.jan.supabase.network.SupabaseApi.rawRequest$suspendImpl(SupabaseApi.kt:25)
at io.github.jan.supabase.network.SupabaseApi$rawRequest$1.invokeSuspend(Unknown Source:15)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7606c21, Dispatchers.Main.immediate]
```

**Comment by jan-tennert** [comment]
This is just a normal exception, and it doesn't even have to do with the Auth plugin itself. As you can see the Exception is a `UnauthorizedRestException`, which is a subtype of `RestException`. If you see a `RestException`s this means that this error is directly from Supabase and the message is just extracted from a response. So to prevent the app closing, just catch this exception:
```kotlin
try {
} catch (e: UnauthorizedRestException) {
    //Handle the error, there is also e.error and e.description to match the error
}
```

**Comment by jeluchu** [comment]
Thank you very much for the information!
