### ISSUE TITLE
[Question]: Trouble Implementing Password Reset on Android with Supabase

### ISSUE THREAD

**Issue by CharlesMoreira1** [supabase-community/supabase-kt#564]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.MD) page for similar problems

### What is your question?

How can I reset the password?

I'm following the documentation, but I don't know what's missing to be able to implement it. Can you help me?

Here's the code as it is:

MainActivity:

```kotlin
class MainActivity : ComponentActivity(), KoinComponent {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val supabaseClient: SupabaseClient by inject()
        supabaseClient.handleDeeplinks(intent)
         ...
    }
}

fun forgetPassword() {
    screenModelScope.launch {
        try {
            supabaseClient.auth.resetPasswordForEmail(email = "myemail@gmail.com")
            _uiState.value = UserState.Success("Success")
        } catch (e: Exception) {
            _uiState.value = UserState.Error("Error: ${e.message}")
        }
    }
}
```

My client:

```kotlin
val supabaseClient = module {
     single {
         createSupabaseClient(
             supabaseUrl = BASE_URL,
             supabaseKey = KEY
         ) {
             install(Auth) {
                 host = "forgot-password"
                 scheme = "beautifulai"
             }
         }
     }
}
```

My manifest:

```xml
<activity
    android:name=".MainActivity"
    android:exported="true"
    android:theme="@style/Theme.MagnificX">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data
            android:host="forgot-password"
            android:scheme="beautifulai"
        />
    </intent-filter>
</activity>
```

My config URL:
![image](https://github.com/supabase-community/supabase-kt/assets/55266908/4f4133b4-995a-49d9-a401-002ddcefebac)

### Relevant log output (optional)

I receive the following error:

`[RequestTokenManager] getToken() -> BAD_AUTHENTICATION. App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/cclog`

**Comment by jan-tennert** [comment]
That error is not related to Supabase, what exactly is the problem?

**Comment by CharlesMoreira1** [comment]
So, I'm not sure exactly what's happening. When I click on the link sent to me, it generates this error:

```
FATAL EXCEPTION: main
Process: com.magnificx.ai, PID: 29225
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.magnificx.ai/com.magnificx.ai.MainActivity}: java.lang.IllegalArgumentException: No access token found
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3897)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4043)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:211)
    at android.os.Looper.loop(Looper.java:300)
    at android.app.ActivityThread.main(ActivityThread.java:8294)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.IllegalArgumentException: No access token found
    at io.github.jan.supabase.gotrue.UtilsKt.invalidArg(Utils.kt:28)
    at io.github.jan.supabase.gotrue.AuthExtensionsKt.parseSessionFromFragment(AuthExtensions.kt:32)
    at io.github.jan.supabase.gotrue.UtilsKt.parseFragmentAndImportSession(Utils.kt:13)
    at io.github.jan.supabase.gotrue.AndroidKt.handleDeeplinks(Android.kt:42)
    at io.github.jan.supabase.gotrue.AndroidKt.handleDeeplinks$default(Android.kt:33)
    at com.magnificx.ai.MainActivity.onCreate(MainActivity.kt:20)
    at android.app.Activity.performCreate(Activity.java:8538)
    at android.app.Activity.performCreate(Activity.java:8502)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1437)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3878)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4043) 
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loopOnce(Looper.java:211) 
    at android.os.Looper.loop(Looper.java:300) 
    at android.app.ActivityThread.main(ActivityThread.java:8294) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028) 

```
I need to add the updateUser function beforehand?

**Comment by CharlesMoreira1** [comment]
> That error is not related to Supabase, what exactly is the problem?

So, I'm not sure exactly what's happening. When I click on the link sent to me, it generates this error:

```
FATAL EXCEPTION: main
Process: com.magnificx.ai, PID: 29225
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.magnificx.ai/com.magnificx.ai.MainActivity}: java.lang.IllegalArgumentException: No access token found
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3897)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4043)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:211)
    at android.os.Looper.loop(Looper.java:300)
    at android.app.ActivityThread.main(ActivityThread.java:8294)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.IllegalArgumentException: No access token found
    at io.github.jan.supabase.gotrue.UtilsKt.invalidArg(Utils.kt:28)
    at io.github.jan.supabase.gotrue.AuthExtensionsKt.parseSessionFromFragment(AuthExtensions.kt:32)
    at io.github.jan.supabase.gotrue.UtilsKt.parseFragmentAndImportSession(Utils.kt:13)
    at io.github.jan.supabase.gotrue.AndroidKt.handleDeeplinks(Android.kt:42)
    at io.github.jan.supabase.gotrue.AndroidKt.handleDeeplinks$default(Android.kt:33)
    at com.magnificx.ai.MainActivity.onCreate(MainActivity.kt:20)
    at android.app.Activity.performCreate(Activity.java:8538)
    at android.app.Activity.performCreate(Activity.java:8502)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1437)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3878)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4043) 
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loopOnce(Looper.java:211) 
    at android.os.Looper.loop(Looper.java:300) 
    at android.app.ActivityThread.main(ActivityThread.java:8294) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028) 

```
I need to add the updateUser function beforehand?

**Comment by CharlesMoreira1** [comment]
I understood the reason. It was because I was clicking on a link sent to the email that had already been clicked.
