### ISSUE TITLE
[Bug]: MissingFieldException while using signUp via Phone

### ISSUE THREAD

**Issue by sivansundar** [supabase-community/supabase-kt#58]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

Hello team. 

I tried using the phone auth functionality of Supabase but I get a `MissingFieldException` while trying to sign up. What I am trying to achieve here is simple. 
- Call the signUp method by passing a phone number.
- Send OTP to the phone number
- Verify the OTP from the client.
- Create user sucessfully.

Below is the code snippet that I used : 

```kotlin
 try {
        val res = supabaseClient.gotrue.signUpWith(Phone){
                phoneNumber = phNumber
                password = passwordValue
            }
            Timber.d("Success")
            Timber.d("$res")
     } catch (exception : Exception) {
            Timber.e(exception)
        }
```

While calling this, I get a `MissingFieldException` and the result isn't being parsed for some reason. But, the user is getting created successfully on Supabase. 

Phone login is enabled with Twillio and the config values have been set as expected. 

I am not sure why this is happening and the OTP isn't getting delivered as well. Library versions are mentioned below. 

Supabase version : 0.8.0
Kotlin version : 1.8.10

Relevant logs are mentioned below.

TIA :)  

### Platform(s)

Android

### Relevant log output

```shell
kotlinx.serialization.MissingFieldException: Fields [id, phone, confirmation_sent_at, created_at, updated_at] are required for type with serial name 'io.github.jan.supabase.gotrue.providers.builtin.Phone.Result', but they were missing
                                                                                                    	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
                                                                                                    	at io.github.jan.supabase.gotrue.providers.builtin.Phone$Result.<init>(Phone.kt:22)
                                                                                                    	at io.github.jan.supabase.gotrue.providers.builtin.Phone$Result$$serializer.deserialize(Phone.kt:22)
                                                                                                    	at io.github.jan.supabase.gotrue.providers.builtin.Phone$Result$$serializer.deserialize(Phone.kt:22)
                                                                                                    	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)
                                                                                                    	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52)
                                                                                                    	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:25)
                                                                                                    	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:115)
                                                                                                    	at io.github.jan.supabase.gotrue.providers.builtin.Phone.decodeResult(Phone.kt:36)
                                                                                                    	at io.github.jan.supabase.gotrue.providers.builtin.Phone.decodeResult(Phone.kt:18)
                                                                                                    	at io.github.jan.supabase.gotrue.providers.builtin.DefaultAuthProvider$DefaultImpls.signUp(DefaultAuthProvider.kt:96)
                                                                                                    	at io.github.jan.supabase.gotrue.providers.builtin.DefaultAuthProvider$signUp$1.invokeSuspend(Unknown Source:17)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by jan-tennert** [comment]
Weird, just tried it and works perfectly fine. Would be good to know what you actually received. Can you somehow check your network traffic (assuming using Android Studio) or check out this dependency: https://ktor.io/docs/client-logging.html#add_dependencies

**Comment by sivansundar** [comment]
This is the only call that I make in this particular screen. However, I can investigate further to see if I can get some additional info and produce it here. As far as the log goes, this is the only one I get.

I am travelling at the moment so I should be able to give you some info by Tuesday.

**Comment by sivansundar** [comment]
Okay so I figured what the issue was. Added `'+'` to the country code followed by the phone number and it worked. Not sure how I missed this. Another observation was adding the country code without `'+'` would go through and you would get a success message but Twillio would return an undelivered status.

At the end of the day, this solved issue. Thanks for checking

**Comment by jan-tennert** [comment]
Yea I thought about adding a check there, but wasn't sure if you always need a `+`

**Comment by sivansundar** [comment]
Yeah. Looks like Twillio expects country codes with a `+`.
