### ISSUE TITLE
[Bug]: androidx.credentials.exceptions.NoCredentialException: No credentials available

### ISSUE THREAD

**Issue by Deorigami** [supabase-community/supabase-kt#659]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### Version(s)

2.5.2

### Kotlin Target(s) and their respective versions

2.0.0

### What happened? (include your code)

I upgraded the version to 2.5.2 because i want to use Google Sign In on iOS but after upgrade from 2.5.0 this error appear on Android

when execute composeAuth.rememberSignInWithGoogle().startFlow()

> Credential exception
                                                                                                    androidx.credentials.exceptions.NoCredentialException: No credentials available
                                                                                                    	at androidx.credentials.CredentialProviderFrameworkImpl.convertToJetpackGetException$credentials_release(CredentialProviderFrameworkImpl.kt:276)
                                                                                                    	at androidx.credentials.CredentialProviderFrameworkImpl$onGetCredential$outcome$2.onError(CredentialProviderFrameworkImpl.kt:152)
                                                                                                    	at androidx.credentials.CredentialProviderFrameworkImpl$onGetCredential$outcome$2.onError(CredentialProviderFrameworkImpl.kt:143)
                                                                                                    	at android.credentials.CredentialManager$GetCredentialTransport.lambda$onError$2(CredentialManager.java:694)
                                                                                                    	at android.credentials.CredentialManager$GetCredentialTransport.$r8$lambda$nlbYav9mLBoE6Yh1vFKCvITF3ks(Unknown Source:0)
                                                                                                    	at android.credentials.CredentialManager$GetCredentialTransport$$ExternalSyntheticLambda2.run(Unknown Source:6)
                                                                                                    	at androidx.credentials.CredentialManager$$ExternalSyntheticLambda0.execute(Unknown Source:0)
                                                                                                    	at android.credentials.CredentialManager$GetCredentialTransport.onError(CredentialManager.java:693)
                                                                                                    	at android.credentials.IGetCredentialCallback$Stub.onTransact(IGetCredentialCallback.java:123)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1344)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1275)

**Comment by jan-tennert** [comment]
@Aaron246 With the old solution, you could just set `setFilterByAuthorizedAccounts` to false and retry the request. Any idea how to do that with `GetSignInWithGoogleOption`?

**Comment by jan-tennert** [comment]
@Aaron246 This issue is probably caused by the Google Sign In change, any ideas?

**Comment by Aaron246** [comment]
I don't think the change has anything to do with this.

@Deorigami can you please check all of these for your project:

1. You have 2 credentials in google cloud console, one web application and one android.
![Screenshot 2024-07-15 000957](https://github.com/user-attachments/assets/5ba98a97-4f83-42d8-93c8-166830ec9ec2)
2. You are using the client ID in web application (the first one in the above screenshot) for

install(ComposeAuth) {
        googleNativeLogin(serverClientId = "google-client-id")
}

in your android project and in the supabase console here
![Screenshot 2024-07-15 001736](https://github.com/user-attachments/assets/aabd3ec4-3753-4417-a12c-9d74f62522f7)
3. The sha-1 certificate and package name in the android credential on the google cloud console (the second credential on google cloud console) is same as the app you are testing right now i.e. if you are testing on debug version or the release version make sure the respective sha-1 key is used in the google cloud console here :
![Screenshot 2024-07-15 002616](https://github.com/user-attachments/assets/9445a9a9-02c8-46ee-9a65-d19a8ec86f70)

If all of these are correct, the issue seems to be with the new Credential Manager API which is being used in ComposeAuth.

Lot of people are facing issues with the API you can see [here](https://github.com/android/identity-samples/issues/53).

**Comment by jan-tennert** [comment]
> I upgraded the version to 2.5.2 because i want to use Google Sign In on iOS but after upgrade from 2.5.0 this error appear on Android
Just to clarify @Deorigami, does 2.5.0 work?

**Comment by Deorigami** [comment]
@jan-tennert Yes 2.5.0 works well on android without this issue, i have to rollback to 2.5.0

**Comment by jan-tennert** [comment]
Hmm, just tried updating one of my old projects and it seems to work fine. Not sure what we can do on this issue other than referring to Google

**Comment by pedromassango** [comment]
For me the issue only happens when you use SHEET:

CRASH
```kotlin 
    val googleAuthState = supabase.composeAuth.rememberSignInWithGoogle(
        type = GoogleDialogType.BOTTOM_SHEET,
        // ...
        }
    )
```

NO CRASH
```kotlin 
    val googleAuthState = supabase.composeAuth.rememberSignInWithGoogle(
        type = GoogleDialogType.DIALOG,
        // ...
        }
    )
```

**Comment by pedromassango** [comment]
Hey any update on this? facing this exact same issue and it is not a misconfiguration
