### ISSUE TITLE
[Bug]: install(GoTrue) throws error in native kotlin

### ISSUE THREAD

**Issue by ferhatwi** [supabase-community/supabase-kt#69]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

```kotlin
suspend fun main() {


    val client = createSupabaseClient(
        supabaseUrl = url,
        supabaseKey = key
    ) {
        install(GoTrue)
        install(Postgrest)
    }
}
```
This code is in the `Playground.kt` file. 
`install(Postgrest)` works fine in both native and Android environment. 
`install(GoTrue)` works fine in Android environment but throws error in native.

### Platform(s)

Native

### Relevant log output

```shell
Exception in thread "main" java.lang.NullPointerException
	at com.russhwolf.settings.NoArgKt.Settings(NoArg.kt:32)
	at io.github.jan.supabase.gotrue.SettingsSessionManager.<init>(SessionManager.kt:26)
	at io.github.jan.supabase.gotrue.GoTrueImpl.<init>(GoTrueImpl.kt:51)
	at io.github.jan.supabase.gotrue.GoTrue$Companion.create(GoTrue.kt:311)
	at io.github.jan.supabase.gotrue.GoTrue$Companion.create(GoTrue.kt:305)
	at io.github.jan.supabase.SupabaseClientBuilder$install$2.invoke(SupabaseClientBuilder.kt:88)
	at io.github.jan.supabase.SupabaseClientBuilder$install$2.invoke(SupabaseClientBuilder.kt:87)
	at io.github.jan.supabase.SupabaseClientImpl.<init>(SupabaseClient.kt:79)
	at io.github.jan.supabase.SupabaseClientBuilder.build(SupabaseClientBuilder.kt:69)
	at io.github.ferhatwi.PlaygroundKt.main(Playground.kt:46)
	at io.github.ferhatwi.PlaygroundKt$main$2.invoke(Playground.kt)
	at io.github.ferhatwi.PlaygroundKt$main$2.invoke(Playground.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at io.github.ferhatwi.PlaygroundKt.main(Playground.kt)
```

**Comment by jan-tennert** [comment]
Which native platform?

**Comment by ferhatwi** [comment]
If code is independent of Android context (e.g.: `Playground.kt` file and a `main` function in it) `install(GoTrue)` method throws error. I basically run the `PlaygroundKt` file, not the `app` configuration.

**Comment by jan-tennert** [comment]
> If code is independent of Android context (e.g.: `Playground.kt` file and a `main` function in it) `install(GoTrue)` method throws error. I basically run the `PlaygroundKt` file, not the `app` configuration.

Okay the problem is that GoTrue couldn't create a default [Settings](https://github.com/russhwolf/multiplatform-settings) instance (for saving & loading sessions), which causes this error (will improve this error in the next version). What you can do is provide a Map-based Settings instance using the multiplatform-settings-test library, which works indecently of the context/platform or pick a different one:
```kts
implementation("com.russhwolf:multiplatform-settings-test:1.0.0")
```
Then in the supabase client builder:
```kotlin
install(GoTrue) {
    sessionManager = SettingsSessionManager(MapSettings())
} 
```
This is also available in the [wiki](https://github.com/supabase-community/supabase-kt/wiki/Session-Saving)

**Comment by ferhatwi** [comment]
Okay, thanks!
