### ISSUE TITLE
[Bug]: Modules don't recognize supabaseUrl on Android environment.

### ISSUE THREAD

**Issue by ferhatwi** [supabase-community/supabase-kt#70]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

```kotlin
package io.github.ferhatwi.presentation.main

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.lifecycle.lifecycleScope
import dagger.hilt.android.AndroidEntryPoint
import io.github.ferhatwi.*
import io.github.jan.supabase.createSupabaseClient
import io.github.jan.supabase.postgrest.Postgrest
import io.github.jan.supabase.postgrest.postgrest
import kotlinx.coroutines.launch
import java.util.*

@AndroidEntryPoint
class Main : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val client = createSupabaseClient(
            supabaseUrl = url,
            supabaseKey = key
        ) {
            install(Postgrest)
        }

        lifecycleScope.launch {
            val y = client.postgrest["test"].select()
            println(y)
        }

        setContent {
            MainScreen()
        }
    }
}
```
`client.postgrest["test"].select()` method sends request to localhost instead of the url that I've provided. `http://localhost?select=%2A` is the exact request.
This exact method works fine in native.

### Platform(s)

Android

### Relevant log output

```shell
/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.ferhatwi, PID: 20952
    io.github.jan.supabase.exceptions.HttpRequestException: HTTP request to http://localhost?select=%2A (GET) failed with message: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at io.github.jan.supabase.network.KtorSupabaseHttpClient.request(KtorSupabaseHttpClient.kt:46)
        at io.github.jan.supabase.network.KtorSupabaseHttpClient$request$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
        at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:355)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:11)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:55)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e00b58a, Dispatchers.Main.immediate]
```

**Comment by jan-tennert** [comment]
Did you print out the url to see if its actually there? Localhost is a fallback url

**Comment by ferhatwi** [comment]
The url at `supabaseUrl = url` is `https://my-project-ref.supabase.co`.
