### ISSUE TITLE
[Bug]: When using signUp with different execution contexts

### ISSUE THREAD

**Issue by estevg** [supabase-community/supabase-kt#74]
### General Info

- [X]  I installed the latest version of Supabase-Kt

### Version(s)

0.8.5

### Target(s)

Android

### What happened? (include your code)

I am implementing the registry and I get an error when I change the context to the IO 

> Here's my code with the IO execution context:

```
class MainActivitySuperBase : AppCompatActivity() {

    private val TAG = "SuperBase"
    lateinit var binding: ActivityMainSuperBaseBinding


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainSuperBaseBinding.inflate(layoutInflater)
        setContentView(binding.root)



        binding.ingresar.setOnClickListener {
            lifecycleScope.launch {
                Log.d(TAG, "RUN  ${Thread.currentThread().name}")
                login()
            }
        }
    }

     private suspend fun login() {
        withContext(Dispatchers.IO) { /* <---- I change the context here */
            kotlin.runCatching {
                client.gotrue.signUpWith(Email) {
                    email = "test@gmail.com"
                    password = "123456789"
                }
            }.onSuccess {
                Log.d(TAG, "Successfully registered! Check your E-Mail to verify your account.")
            }.onFailure {
                Log.d(TAG, "There was an error while registering: ${it}")
            }
        }
    }
```

> And the error I get is:
``` 
 There was an error while registering: java.lang.ExceptionInInitializerError 
 or 
 There was an error while registering: null
```

But when I change the execution context to Main it works fine. 

Here's my code with the Main execution context

```
class MainActivitySuperBase : AppCompatActivity() {

    private val TAG = "SuperBase"
    lateinit var binding: ActivityMainSuperBaseBinding


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainSuperBaseBinding.inflate(layoutInflater)
        setContentView(binding.root)



        binding.ingresar.setOnClickListener {
            lifecycleScope.launch {
                Log.d(TAG, "RUN  ${Thread.currentThread().name}")
                login()
            }
        }
    }

    private suspend fun login() {
        kotlin.runCatching {
            client.gotrue.signUpWith(Email) {
                email = "test1@gmail.com"
                password = "123456789"
            }
        }.onSuccess {
            Log.d(TAG, "Successfully registered! Check your E-Mail to verify your account.")
        }.onFailure {
            Log.d(TAG, "There was an error while registering: ${it}")
        }
    }
}
```

I would like to know if this is a bug or an implementation issue.
I am learning android and from what I have learned the use of Dispatchers.IO is used for input/output intensive operations, such as reading or writing files, network calls, etc.  
If you can help me I would really appreciate it.

### Relevant log output (optional)

```shell
There was an error while registering: java.lang.ExceptionInInitializerError 
or 
There was an error while registering: null
```
```

**Comment by jan-tennert** [comment]
Can you print out the full stack trace of the exception?

```kotlin
.onFailure {
    it.printStackTrace()
    Log.d(TAG, "There was an error while registering: ${it}")
}

**Comment by estevg** [comment]
> Can youyou print out the full stack tracetrace of the exceptionexception?
> 
> ```kotlin
> .onFailure {
>     it.printStackTrace()
>     Log.d(TAG, "There was an error while registering: ${it}")
> }
> ```


> I get this error


```kotlin
D/EGL_emulation: app_time_stats: avg=535.13ms min=1.49ms max=25708.20ms count=49
D/SuperBase: RUN  DefaultDispatcher-worker-1
I/.estudioandroi: Rejecting re-init on previously-failed class java.lang.Class<com.example.estudioandroid.superbase.MainActivitySuperBaseKt>: java.lang.ExceptionInInitializerError: 
    (Throwable with no stack trace)
W/System.err: java.lang.NoClassDefFoundError: com.example.estudioandroid.superbase.MainActivitySuperBaseKt
W/System.err:     at com.example.estudioandroid.superbase.MainActivitySuperBaseKt.getClient(MainActivitySuperBase.kt:21)
W/System.err:     at com.example.estudioandroid.superbase.MainActivitySuperBase.login(MainActivitySuperBase.kt:53)
W/System.err:     at com.example.estudioandroid.superbase.MainActivitySuperBase.access$login(MainActivitySuperBase.kt:30)
W/System.err:     at com.example.estudioandroid.superbase.MainActivitySuperBase$onCreate$1$1.invokeSuspend(MainActivitySuperBase.kt:46)
W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
W/System.err:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
W/System.err: Caused by: java.lang.ExceptionInInitializerError
W/System.err: 	... 12 more
W/System.err: Caused by: java.lang.IllegalStateException: Method addObserver must be called on the main thread
W/System.err:     at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.kt:296)
W/System.err:     at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:174)
W/System.err:     at io.github.jan.supabase.gotrue.SetupPlatformKt.addLifecycleCallbacks(setupPlatform.kt:32)
W/System.err:     at io.github.jan.supabase.gotrue.SetupPlatformKt.setupPlatform(setupPlatform.kt:25)
W/System.err:     at io.github.jan.supabase.gotrue.GoTrueImpl.<init>(GoTrueImpl.kt:61)
W/System.err:     at io.github.jan.supabase.gotrue.GoTrue$Companion.create(GoTrue.kt:313)
W/System.err:     at io.github.jan.supabase.gotrue.GoTrue$Companion.create(GoTrue.kt:307)
W/System.err:     at io.github.jan.supabase.SupabaseClientBuilder$install$2.invoke(SupabaseClientBuilder.kt:88)
W/System.err:     at io.github.jan.supabase.SupabaseClientBuilder$install$2.invoke(SupabaseClientBuilder.kt:87)
W/System.err:     at io.github.jan.supabase.SupabaseClientImpl.<init>(SupabaseClient.kt:79)
W/System.err:     at io.github.jan.supabase.SupabaseClientBuilder.build(SupabaseClientBuilder.kt:69)
W/System.err:     at com.example.estudioandroid.superbase.MainActivitySuperBaseKt.<clinit>(MainActivitySuperBase.kt:65)
W/System.err: 	... 12 more
D/SuperBase: There was an error while registering: com.example.estudioandroid.superbase.MainActivitySuperBaseKt



```

**Comment by jan-tennert** [comment]
> > Can youyou print out the full stack tracetrace of the exceptionexception?
> > ```kotlin
> > .onFailure {
> >     it.printStackTrace()
> >     Log.d(TAG, "There was an error while registering: ${it}")
> > }
> > ```
> 
> > I get this error
> 
> ```kotlin
> D/EGL_emulation: app_time_stats: avg=535.13ms min=1.49ms max=25708.20ms count=49
> D/SuperBase: RUN  DefaultDispatcher-worker-1
> I/.estudioandroi: Rejecting re-init on previously-failed class java.lang.Class<com.example.estudioandroid.superbase.MainActivitySuperBaseKt>: java.lang.ExceptionInInitializerError: 
>     (Throwable with no stack trace)
> W/System.err: java.lang.NoClassDefFoundError: com.example.estudioandroid.superbase.MainActivitySuperBaseKt
> W/System.err:     at com.example.estudioandroid.superbase.MainActivitySuperBaseKt.getClient(MainActivitySuperBase.kt:21)
> W/System.err:     at com.example.estudioandroid.superbase.MainActivitySuperBase.login(MainActivitySuperBase.kt:53)
> W/System.err:     at com.example.estudioandroid.superbase.MainActivitySuperBase.access$login(MainActivitySuperBase.kt:30)
> W/System.err:     at com.example.estudioandroid.superbase.MainActivitySuperBase$onCreate$1$1.invokeSuspend(MainActivitySuperBase.kt:46)
> W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> W/System.err:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
> W/System.err:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
> W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
> W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
> W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> W/System.err: Caused by: java.lang.ExceptionInInitializerError
> W/System.err: 	... 12 more
> W/System.err: Caused by: java.lang.IllegalStateException: Method addObserver must be called on the main thread
> W/System.err:     at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.kt:296)
> W/System.err:     at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:174)
> W/System.err:     at io.github.jan.supabase.gotrue.SetupPlatformKt.addLifecycleCallbacks(setupPlatform.kt:32)
> W/System.err:     at io.github.jan.supabase.gotrue.SetupPlatformKt.setupPlatform(setupPlatform.kt:25)
> W/System.err:     at io.github.jan.supabase.gotrue.GoTrueImpl.<init>(GoTrueImpl.kt:61)
> W/System.err:     at io.github.jan.supabase.gotrue.GoTrue$Companion.create(GoTrue.kt:313)
> W/System.err:     at io.github.jan.supabase.gotrue.GoTrue$Companion.create(GoTrue.kt:307)
> W/System.err:     at io.github.jan.supabase.SupabaseClientBuilder$install$2.invoke(SupabaseClientBuilder.kt:88)
> W/System.err:     at io.github.jan.supabase.SupabaseClientBuilder$install$2.invoke(SupabaseClientBuilder.kt:87)
> W/System.err:     at io.github.jan.supabase.SupabaseClientImpl.<init>(SupabaseClient.kt:79)
> W/System.err:     at io.github.jan.supabase.SupabaseClientBuilder.build(SupabaseClientBuilder.kt:69)
> W/System.err:     at com.example.estudioandroid.superbase.MainActivitySuperBaseKt.<clinit>(MainActivitySuperBase.kt:65)
> W/System.err: 	... 12 more
> D/SuperBase: There was an error while registering: com.example.estudioandroid.superbase.MainActivitySuperBaseKt
> ```

How do you create the supabase client instance? The error says you are not doing that on the main thread

**Comment by estevg** [comment]
I am implementing it in this way 
@jan-tennert 

```kotlin

package com.example.estudioandroid.superbase

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import androidx.lifecycle.lifecycleScope
import com.example.estudioandroid.databinding.ActivityMainSuperBaseBinding
import io.github.jan.supabase.createSupabaseClient
import io.github.jan.supabase.gotrue.GoTrue
import io.github.jan.supabase.gotrue.gotrue
import io.github.jan.supabase.gotrue.providers.builtin.Email
import io.github.jan.supabase.postgrest.Postgrest
import io.github.jan.supabase.postgrest.postgrest
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers

import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable

var client = createSupabaseClient(
    supabaseUrl = "xxxx",
    supabaseKey = "xxxx",
) {
    install(Postgrest)
    install(GoTrue)
}


class MainActivitySuperBase : AppCompatActivity() {

    private val TAG = "SuperBase"
    lateinit var binding: ActivityMainSuperBaseBinding


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainSuperBaseBinding.inflate(layoutInflater)
        setContentView(binding.root)



        binding.ingresar.setOnClickListener {
            lifecycleScope.launch(Dispatchers.IO) {
                Log.d(TAG, "RUN  ${Thread.currentThread().name}")
                login()
            }
        }
    }

    private suspend fun login() {
        kotlin.runCatching {
            client.gotrue.signUpWith(Email) {
                email = "test1@gmail.com"
                password = "123456789"
            }
        }.onSuccess {
            Log.d(TAG, "Successfully registered! Check your E-Mail to verify your account.")
        }.onFailure {
            it.printStackTrace()
            Log.d(TAG, "There was an error while registering: ${it.message}")
        }
    }
}

```

**Comment by jan-tennert** [comment]
Is there a reason that `client` is a var and not a val? Also you should probably initialize the client within your activity rather than as a static variable. (or use dependency injection but you are probably not using that)

**Comment by estevg** [comment]
Actually I was just testing I don't know why I had it in var and not in var. 
And when passing it inside the activity it works correctly, it was probably a bad implementation on my part.
Now I will pass it with dependency injection. 
Thank you very much @jan-tennert 



```kotlin

package com.example.estudioandroid.superbase

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import androidx.lifecycle.lifecycleScope
import com.example.estudioandroid.databinding.ActivityMainSuperBaseBinding
import io.github.jan.supabase.SupabaseClient
import io.github.jan.supabase.createSupabaseClient
import io.github.jan.supabase.gotrue.GoTrue
import io.github.jan.supabase.gotrue.gotrue
import io.github.jan.supabase.gotrue.providers.builtin.Email
import io.github.jan.supabase.postgrest.Postgrest
import io.github.jan.supabase.postgrest.postgrest
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers

import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable




class MainActivitySuperBase : AppCompatActivity() {

    private val TAG = "SuperBase"
    lateinit var binding: ActivityMainSuperBaseBinding


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainSuperBaseBinding.inflate(layoutInflater)
        setContentView(binding.root)

        val client = createSupabaseClient(
            supabaseUrl = "xxxxx",
            supabaseKey = "xxxxx",
        ) {
            install(Postgrest)
            install(GoTrue)
        }

        binding.ingresar.setOnClickListener {
            lifecycleScope.launch(Dispatchers.IO) {
                Log.d(TAG, "RUN  ${Thread.currentThread().name}")
                login(client)
            }
        }
    }

    private suspend fun login(client: SupabaseClient) {
        kotlin.runCatching {
            client.gotrue.signUpWith(Email) {
                email = "test1@gmail.com"
                password = "123456789"
            }
        }.onSuccess {
            Log.d(TAG, "Successfully registered! Check your E-Mail to verify your account.")
        }.onFailure {
            it.printStackTrace()
            Log.d(TAG, "There was an error while registering: ${it.message}")
        }
    }
}

```
