### ISSUE TITLE
[Question]: Connection reset by peer happening intermittently

### ISSUE THREAD

**Issue by vipulyaara** [supabase-community/supabase-kt#766]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### What is your question?

I am using `supabase-kt:3.0.1`. It happens intermittently; opening a page will work one time and not the other. I cannot figure out if there is something wrong with the project dependencies (ktor) or Supabase.

Full logs are attached below. It seems to be happening with all the fetches across the tables as well as realtime and auth calls. The project is KMP running on android and desktop (mac). It happens on both platforms. Ktor dependendency is `CIO 3.0.0-rc01`.

```
Error while trying to connect to realtime websocket. Trying again in 7s

URL: wss://kkeos....supabase.co/realtime/v1/websocket?apikey=eyJh...&vsn=1.0.0

java.io.IOException: Connection reset by peer
```

### Relevant log output (optional)

```shell
GET request to endpoint /rest/v1/item_detail failed with exception Connection reset by peer (Ask Gemini)
                                                                                                    java.io.IOException: Connection reset by peer
                                                                                                    	at io.ktor.utils.io.CloseToken.<init>(CloseToken.kt:27)
                                                                                                    	at io.ktor.utils.io.ByteChannel.cancel(ByteChannel.kt:133)
                                                                                                    	at io.ktor.utils.io.ByteWriteChannelOperationsKt$writer$job$1.invokeSuspend(ByteWriteChannelOperations.kt:151)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
                                                                                                    Caused by: java.io.IOException: Connection reset by peer
                                                                                                    	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
                                                                                                    	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
                                                                                                    	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
                                                                                                    	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
                                                                                                    	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:421)
                                                                                                    	at io.ktor.network.sockets.CIOReaderKt.readFrom$lambda$0(CIOReader.kt:135)
                                                                                                    	at io.ktor.network.sockets.CIOReaderKt.$r8$lambda$Js9p8Q8zGEhfyoRx4vADpPJikgM(Unknown Source:0)
                                                                                                    	at io.ktor.network.sockets.CIOReaderKt$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
                                                                                                    	at io.ktor.utils.io.ByteWriteChannelOperations_jvmKt.write(ByteWriteChannelOperations.jvm.kt:28)
                                                                                                    	at io.ktor.utils.io.ByteWriteChannelOperations_jvmKt.write$default(ByteWriteChannelOperations.jvm.kt:24)
                                                                                                    	at io.ktor.network.sockets.CIOReaderKt.readFrom(CIOReader.kt:134)
                                                                                                    	at io.ktor.network.sockets.CIOReaderKt.access$readFrom(CIOReader.kt:1)
                                                                                                    	at io.ktor.network.sockets.CIOReaderKt$attachForReadingDirectImpl$1.invokeSuspend(CIOReader.kt:110)
                                                                                                    	... 8 more
2024-10-26 15:05:51.502 30976-30976 <no-tag>                com.kafka.user.debug                 E  io.github.jan.supabase.exceptions.HttpRequestException: HTTP request to https://kkeosgnragzpgsbaocjl.supabase.co/rest/v1/item_detail?item_id=eq.gutenberg_19033&select=%2A (GET) failed with message: Connection reset by peer (Ask Gemini)
                                                                                                    	at io.github.jan.supabase.network.KtorSupabaseHttpClient.request(KtorSupabaseHttpClient.kt:71)
                                                                                                    	at io.github.jan.supabase.network.KtorSupabaseHttpClient$request$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
2024-10-26 15:06:05.407 30976-32470 Supabase-Core           com.kafka.user.debug                

```

**Comment by jan-tennert** [comment]
The first thing you could try is to update the CIO engine to `3.0.0` and see if that changes anything

**Comment by vipulyaara** [comment]
ah my bad, I reported the wrong version. I am already using Ktor 3.0.0.

**Comment by vipulyaara** [comment]
It's also happening with a previous version of code that worked fine. Also with the python scripts I have for inserting the data in tables. So it's definitely not related to kotlin codebase, and somehow my supabse account/project. Any idea how I can debug that?

**Comment by jan-tennert** [comment]
So this not just happens with the Kotlin library?

**Comment by vipulyaara** [comment]
Yes exactly. We can close the issue. I'd still love to have some direction if you have an idea what could be wrong. Supabase logs don't show these errors.

**Comment by jan-tennert** [comment]
As you said it happens on multiple devices and across libraries, maybe a network issue on your end? In any case, maybe you could look at [Monitor & Fix](https://supabase.com/docs/guides/monitoring-troubleshooting) or try to ask in the Supabase Github discussions/Discord/support. I haven't had that problem, so I'm not sure.
