### ISSUE TITLE
[Bug]: Realtime Websocket Connection Crashes

### ISSUE THREAD

**Issue by Shabinder** [supabase-community/supabase-kt#777]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### Version(s)

3.0.1

### Kotlin Target(s) and their respective versions

Android 14, 13

### What happened? (include your code)

I am seeing these in my crashlytics with a huge frequency, and the only place I use websockets are supabase realtime, anyidea where these are happening, and the place to handle these ?

```
          Fatal Exception: java.net.SocketException: Software caused connection abort
       at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
       at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
       at java.net.SocketInputStream.read(SocketInputStream.java:173)
       at java.net.SocketInputStream.read(SocketInputStream.java:143)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:985)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:949)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:864)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:837)
       at okio.InputStreamSource.read(InputStreamSource.java:93)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:153)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:211)
       at okio.RealBufferedSource.require(RealBufferedSource.kt)
       at okio.RealBufferedSource.readByte(RealBufferedSource.kt:214)
       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
       at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
        
```

**Comment by Shabinder** [comment]
Also these as well:
          
```
          
Fatal Exception: java.io.EOFException:
       at okio.RealBufferedSource.require(RealBufferedSource.kt:204)
       at okio.RealBufferedSource.readByte(RealBufferedSource.kt:214)
       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
       at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
        
```

**Comment by brezinajn** [comment]
Is the first one by any chance related to the application pausing while in the background? I used to have that one as well. I'd bet you're not cleaning up properly.

**Comment by Shabinder** [comment]
> Is the first one by any chance related to the application pausing while in the background? I used to have that one as well. I'd bet you're not cleaning up properly.

Yeah I can improve that, any idea about the other two ?

**Comment by jan-tennert** [comment]
The last one looks a network issue, but the Realtime module normally catches any network related exception and tries to reconnect. There is no Ktor/Supabase related function in the stacktrace, so probably uncatchable for us and the only thing you could do is look into is the OkHttp client settings when using it as a Ktor engine. Alone are such exceptions always pretty hard to debug.

**Comment by Shabinder** [comment]
I was able to fix most by closing out the connection whenever app went into background, but below still rarely happens:
```
Fatal Exception: java.io.EOFException:
       at okio.RealBufferedSource.require(RealBufferedSource.kt:204)
       at okio.RealBufferedSource.readByte(RealBufferedSource.kt:214)
       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
       at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
        
```

**Comment by jan-tennert** [comment]
> I believe I was able to fix most by closing out the connection whenever app went into background, since haven't been reported yet, but below still rarely happens:
> 
> ```
> Fatal Exception: java.io.EOFException:
>        at okio.RealBufferedSource.require(RealBufferedSource.kt:204)
>        at okio.RealBufferedSource.readByte(RealBufferedSource.kt:214)
>        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
>        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
>        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
>        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
>        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
>        at java.lang.Thread.run(Thread.java:1012)
>         
> ```

Hmm, I found [this](https://github.com/square/okhttp/issues/3113) issue for Okio. Do you by any chance see the debug logs (which also log pings to the realtime websocket)?
Would be interesting.

**Comment by Shabinder** [comment]
> Hmm, I found [this](https://github.com/square/okhttp/issues/3113) issue for Okio. Do you by any chance see the debug logs (which also log pings to the realtime websocket)? Would be interesting.

Thanks for linking that issue, will revisit since I can still see these crashes a considerate number of times.

**Comment by Shabinder** [comment]
@jan-tennert I tried but for some reason I am not able to repro this,
Also, on a second thought, shouldn't this be caught at library level, and a reconnect strategy be in place,

Since Ideally clients, unless explicitly needed shouldn't care about connection handling and the fail-safe logic associated.

**Comment by jan-tennert** [comment]
As I already mentioned in a previous [comment](https://github.com/supabase-community/supabase-kt/issues/777#issuecomment-2460070870)
> The last one looks a network issue, but the Realtime module normally catches any network related exception and tries to reconnect. There is no Ktor/Supabase related function in the stacktrace, like in the other exceptions, so probably uncatchable for us

The exceptions you are sharing are not normal connection loss issues. And since it's unreproceable and a ktor engine specific error, there is little we can do.

**Comment by TiagoLira** [comment]
Hi @jan-tennert sorry to reopen, but our users are having crashes similar to the first SocketException above.
The error happens every time when the device loses internet connection, you can try it by turning off wifi while the socket is open.

It seems to be a non-fatal error on most devices, but according to crashlytics it's crashing the app on some Samsung devices.
I've looked on okio forums and according to this thread, it's an exception that must be handled by clients.
https://github.com/square/okio/issues/1167

We have error handling on all realtime code, but it doesn't catch it.
Can you please check if the exception can be handled on your side?

Here is the stack trace:
```
Fatal Exception: java.net.SocketException
Software caused connection abort
java.net.SocketInputStream.socketRead0 (SocketInputStream.java)
java.net.SocketInputStream.socketRead (SocketInputStream.java:118)
java.net.SocketInputStream.read (SocketInputStream.java:173)
java.net.SocketInputStream.read (SocketInputStream.java:143)
com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket (ConscryptEngineSocket.java:985)
com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket (ConscryptEngineSocket.java:949)
com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable (ConscryptEngineSocket.java:864)
com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read (ConscryptEngineSocket.java:837)
okio.InputStreamSource.read (JvmOkio.kt:93)
okio.AsyncTimeout$source$1.read (AsyncTimeout.kt:153)
okio.RealBufferedSource.request (RealBufferedSource.kt:211)
okio.RealBufferedSource.require (RealBufferedSource.kt:204)
okio.RealBufferedSource.readByte (RealBufferedSource.kt:214)
okhttp3.internal.ws.WebSocketReader.readHeader (WebSocketReader.kt:119)
okhttp3.internal.ws.WebSocketReader.processNextFrame (WebSocketReader.kt:102)
okhttp3.internal.ws.RealWebSocket.loopReader (RealWebSocket.kt:293)
okhttp3.internal.ws.RealWebSocket$connect$1.onResponse (RealWebSocket.kt:195)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:519)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
java.lang.Thread.run (Thread.java:1012)
```

And the device models where it is crashing, according to crashlytics:
- Samsung Galaxy S24 Ultra
- Samsung Galaxy S23 Ultra
- Samsung Galaxy A53 5G
- Samsung Galaxy S21 Ultra 5G
- Samsung Galaxy Z Fold6
- Samsung Galaxy Z Fold4

**Comment by jan-tennert** [comment]
@TiagoLira Just tested again with the chat demo sample, and when using the Okio Engine and disconnecting from the internet while having the app open, I get the expected result with with your exact exception:
```kotlin
2025-01-27 14:04:56.509 21468-21578 Supabase-Realtime       io.github.jan.supabase.android       E  Error while listening for messages. Trying again in 7s
                                                                                                    java.net.SocketException: Software caused connection abort
                                                                                                    	at java.net.SocketInputStream.socketRead0(Native Method)
                                                                                                    	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:173)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:143)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:983)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:947)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:862)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:835)
                                                                                                    	at okio.InputStreamSource.read(JvmOkio.kt:93)
                                                                                                    	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:153)
                                                                                                    	at okio.RealBufferedSource.request(RealBufferedSource.kt:230)
                                                                                                    	at okio.RealBufferedSource.require(RealBufferedSource.kt:223)
                                                                                                    	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:233)
                                                                                                    	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
                                                                                                    	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

And after 7s, it tried to reconnected 🤔

**Comment by jan-tennert** [comment]
Everything in Realtime is wrapped in a try-catch block:
https://github.com/supabase-community/supabase-kt/blob/a833da356bb6ff5e7ab49e2b8b215f48f87d6d8f/Realtime/src/commonMain/kotlin/io/github/jan/supabase/realtime/RealtimeImpl.kt#L76-L95
https://github.com/supabase-community/supabase-kt/blob/a833da356bb6ff5e7ab49e2b8b215f48f87d6d8f/Realtime/src/commonMain/kotlin/io/github/jan/supabase/realtime/RealtimeImpl.kt#L126-L140

**Comment by jan-tennert** [comment]
@TiagoLira, yea we can do that. Opened up a PR: https://github.com/supabase-community/supabase-kt/pull/848
Will release a minor version later today, let me know if you get any more crashes after this version!

**Comment by TiagoLira** [comment]
Perfect, thank you!
