### ISSUE TITLE
[Question]: Is any HttpClient config needed to use Realtime?

### ISSUE THREAD

**Issue by jollygreenegiant** [supabase-community/supabase-kt#81]
### What is your question?

When attempting to connect to realtime, I'm getting the following error when calling `supabaseClient.realtime.connect()`:

```
Error while trying to connect to realtime websocket. Trying again in 7s
java.lang.IllegalArgumentException: Engine doesn't support WebSocketCapability
	at io.ktor.client.engine.HttpClientEngine$DefaultImpls.checkExtensions(HttpClientEngine.kt:105)
	at io.ktor.client.engine.HttpClientEngine$DefaultImpls.access$checkExtensions(HttpClientEngine.kt:24)
	at io.ktor.client.engine.HttpClientEngine$install$1.invokeSuspend(HttpClientEngine.kt:68)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(Unknown Source:15)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(Unknown Source:4)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.client.plugins.HttpSend$DefaultSender.execute(HttpSend.kt:138)
	at io.ktor.client.plugins.HttpTimeout$Plugin$install$1.invokeSuspend(HttpTimeout.kt:146)
	at io.ktor.client.plugins.HttpTimeout$Plugin$install$1.invoke(Unknown Source:15)
	at io.ktor.client.plugins.HttpTimeout$Plugin$install$1.invoke(Unknown Source:6)
	at io.ktor.client.plugins.HttpSend$InterceptedSender.execute(HttpSend.kt:116)
	at io.ktor.client.plugins.HttpRedirect$Plugin$install$1.invokeSuspend(HttpRedirect.kt:64)
	at io.ktor.client.plugins.HttpRedirect$Plugin$install$1.invoke(Unknown Source:15)
	at io.ktor.client.plugins.HttpRedirect$Plugin$install$1.invoke(Unknown Source:6)
	at io.ktor.client.plugins.HttpSend$InterceptedSender.execute(HttpSend.kt:116)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:151)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invoke(Unknown Source:13)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invoke(Unknown Source:6)
	at io.ktor.client.plugins.HttpSend$InterceptedSender.execute(HttpSend.kt:116)
	at io.ktor.client.plugins.HttpSend$Plugin$install$1.invokeSuspend(HttpSend.kt:104)
	at io.ktor.client.plugins.HttpSend$Plugin$install$1.invoke(Unknown Source:15)
	at io.ktor.client.plugins.HttpSend$Plugin$install$1.invoke(Unknown Source:4)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
	at io.ktor.client.plugins.websocket.WebSockets$Plugin$install$1.invokeSuspend(WebSockets.kt:169)
	at io.ktor.client.plugins.websocket.WebSockets$Plugin$install$1.invoke(Unknown Source:13)
	at io.ktor.client.plugins.websocket.WebSockets$Plugin$install$1.invoke(Unknown Source:4)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:130)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(Unknown Source:13)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(Unknown Source:4)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invokeSuspend(HttpRequestLifecycle.kt:38)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(Unknown Source:11)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(Unknown Source:4)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.client.HttpClient.execute$ktor_client_core(HttpClient.kt:191)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:108)
	at io.ktor.client.plugins.websocket.BuildersKt$webSocketSession$2.invokeSuspend(builders.kt:239)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

I attempted to fix this by adding a custom HttpClient that has WebSockets installed, but that didn't fix the problem:
```
createSupabaseClient(
    supabaseUrl = "my_url",
    supabaseKey = "my_key"
) {
    // other stuff
    install(Realtime)
    httpEngine = HttpClient(Android) {
        install(WebSockets)
    }.engine
}
```

Is there any other setup needed to get Realtime working?  I followed the wiki and setup docs, and checked out the Realtime demo, but it seems like I'm missing something.

**Comment by jan-tennert** [comment]
![image](https://user-images.githubusercontent.com/26686035/228956561-195ea7ef-a442-4e74-93c7-6aac46c0ef1c.png)
Seems like the Android engine doesn't support Websockets. You should be able to use CIO or OkHttp

**Comment by jollygreenegiant** [comment]
Okay I've got the connection working now (thank you!) but having trouble getting realtime updates.

Here's what I've got: 

```
private val channel = supabaseClient.realtime.createChannel("currentBooks")

init {
    coroutineScope.launch {
        kotlin.runCatching {
            supabaseClient.realtime.connect()
        }.onFailure {
            it.printStackTrace()
        }
    }
}

suspend fun getCurrentBooksListener(forUserId: String): Flow<PostgresAction.Update> {
    val flow = channel.postgresChangeFlow<PostgresAction.Update>("public") {
        table = "user_books"
    }
    channel.join()
    return flow
}
```
and then in my viewmodel:
```
supabaseRepository.getCurrentBooksListener(forUserId = authRepository.userId ?: "").collect {
    println("postgresupdate")

    // update viewmodel state
}
```

The `collect` call in the viewmodel is never getting triggered.  Am I missing something?

**Comment by jan-tennert** [comment]
> 

Could be caused by many things. You can enable logging by calling `Napier.base(DebugAntilog())` somewhere at the start of your code, and you should see things like `Joining channel...`, `Joining realtime socket with body $body`, `Joined channel $channel` and then channel events.
On top of that:
- Do you have replication/realtime enabled for the corresponding table?
- Is your table protected by RLS (and does your current session have enough permission)

**Comment by jollygreenegiant** [comment]
Yeah so I'm getting those events when I filter by `Realtime` in logcat:

```
Connected to realtime websocket!
Joining channel realtime:currentBooks
Joining realtime socket with body {"config":{"broadcast":{"ack":false,"self":false},"presence":{"key":""},"postgres_changes":[{"schema":"public","table":"user_books","event":"UPDATE"}]},"access_token":"<ACCESS_TOKEN>"}
Received message {"event":"phx_reply","payload":{"response":{"postgres_changes":[{"id":19251975,"event":"UPDATE","schema":"public","table":"user_books"}]},"status":"ok"},"ref":null,"topic":"realtime:currentBooks"}
Received event phx_reply for channel realtime:currentBooks
Received message {"event":"presence_state","payload":{},"ref":null,"topic":"realtime:currentBooks"}
Received event presence_state for channel realtime:currentBooks
Received message {"event":"system","payload":{"channel":"currentBooks","extension":"postgres_changes","message":"Subscribed to PostgreSQL","status":"ok"},"ref":null,"topic":"realtime:currentBooks"}
Received event system for channel realtime:currentBooks
Joined channel realtime:currentBooks
Sending heartbeat
Received message {"event":"phx_reply","payload":{"response":{},"status":"ok"},"ref":"1","topic":"phoenix"}
Heartbeat received
Sending heartbeat
Received message {"event":"phx_reply","payload":{"response":{},"status":"ok"},"ref":"2","topic":"phoenix"}
```

Replication and realtime are both enabled for the `user_books` table, and RLS is turned off for that table as well

**Comment by jollygreenegiant** [comment]
That did it!  Thank your for your help!

**Comment by jollygreenegiant** [comment]
I'm still struggling to get this working consistently, but don't want to bombard you with new issues - I've gotten the realtime updates to work sporadically, where occasionally they come through as expected, but more often than not, no updates are coming through the flow.

I'm getting heartbeats from the websocket, so I know it's at least connected:
```
Sending heartbeat
Received message {"event":"phx_reply","payload":{"response":{},"status":"ok"},"ref":"51","topic":"phoenix"}
Heartbeat received
```
I've declared my repository, SupabaseClient, and RealtimeChannel as singletons with Koin, to attempt to avoid duplicates and race conditions.

I'm calling the realtime channel like this:

```
suspend fun getCurrentBooksListener(
    forUserId: String,
    scope: CoroutineScope,
    onEach: (PostgresAction) -> Unit
) {
    kotlin.runCatching {
        supabaseClient.realtime.connect()
        channel.postgresChangeFlow<PostgresAction>("public") {
            table = "user_books"
        }.onEach {
            onEach(it)
        }.launchIn(scope)

        channel.join()
    }.onFailure {
        it.printStackTrace()
    }
}
```
in this case, the `onEach()` function is not getting triggered when I update values in the Supabase dashboard.  I understand this might be a little vague, so if there's more info I could give that would be helpful, let me know

**Comment by jan-tennert** [comment]
> I'm still struggling to get this working consistently, but don't want to bombard you with new issues - I've gotten the realtime updates to work sporadically, where occasionally they come through as expected, but more often than not, no updates are coming through the flow.
> 
> I'm getting heartbeats from the websocket, so I know it's at least connected:
> 
> ```
> Sending heartbeat
> Received message {"event":"phx_reply","payload":{"response":{},"status":"ok"},"ref":"51","topic":"phoenix"}
> Heartbeat received
> ```
> 
> I've declared my repository, SupabaseClient, and RealtimeChannel as singletons with Koin, to attempt to avoid duplicates and race conditions.
> 
> I'm calling the realtime channel like this:
> 
> ```
> suspend fun getCurrentBooksListener(
>     forUserId: String,
>     scope: CoroutineScope,
>     onEach: (PostgresAction) -> Unit
> ) {
>     kotlin.runCatching {
>         supabaseClient.realtime.connect()
>         channel.postgresChangeFlow<PostgresAction>("public") {
>             table = "user_books"
>         }.onEach {
>             onEach(it)
>         }.launchIn(scope)
> 
>         channel.join()
>     }.onFailure {
>         it.printStackTrace()
>     }
> }
> ```
> 
> in this case, the `onEach()` function is not getting triggered when I update values in the Supabase dashboard. I understand this might be a little vague, so if there's more info I could give that would be helpful, let me know

Do you see an event in the debug logs when you update the values in the dashboard?

**Comment by jan-tennert** [comment]
Also does this happen with all PostgresAction types?

**Comment by jollygreenegiant** [comment]
Just tried again, and I'm no longer able to reproduce the problem, without having changed the code 🙃 

I'll comment here if it starts happening again, and let you know if it happens with all event types.  As far as the logs, I was only ever getting the heartbeat, not any logs about the changes coming through.  Now that things are working as expected though, I am getting those logs with the updated data.
